/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface affx_fusionConstants {
  public final static int PARAMETER_VALUE_SIGNED_INTEGRAL = affx_fusionJNI.get_PARAMETER_VALUE_SIGNED_INTEGRAL();
  public final static int PARAMETER_VALUE_UNSIGNED_INTEGRAL = affx_fusionJNI.get_PARAMETER_VALUE_UNSIGNED_INTEGRAL();
  public final static int PARAMETER_VALUE_FLOATING_POINT = affx_fusionJNI.get_PARAMETER_VALUE_FLOATING_POINT();
  public final static int PARAMETER_VALUE_STRING8_TYPE = affx_fusionJNI.get_PARAMETER_VALUE_STRING8_TYPE();
  public final static int PARAMETER_VALUE_STRING16_TYPE = affx_fusionJNI.get_PARAMETER_VALUE_STRING16_TYPE();
  public final static String AFFY_EXPR_PS = affx_fusionJNI.get_AFFY_EXPR_PS();
  public final static String AFFY_GENO_PS = affx_fusionJNI.get_AFFY_GENO_PS();
  public final static String AFFY_TAG_PS = affx_fusionJNI.get_AFFY_TAG_PS();
  public final static String AFFY_RESEQ_PS = affx_fusionJNI.get_AFFY_RESEQ_PS();
  public final static String AFFY_CNTRL_PS = affx_fusionJNI.get_AFFY_CNTRL_PS();
  public final static String ARRAY_FILE_TYPE_IDENTIFIER = affx_fusionJNI.get_ARRAY_FILE_TYPE_IDENTIFIER();
  public final static int MAX_CDF_PROBE_SET_NAME_LENGTH = affx_fusionJNI.get_MAX_CDF_PROBE_SET_NAME_LENGTH();
  public final static String AUDIT_USER_TAG = affx_fusionJNI.get_AUDIT_USER_TAG();
  public final static String AUDIT_DATE_TAG = affx_fusionJNI.get_AUDIT_DATE_TAG();
  public final static String AUDIT_TIME_TAG = affx_fusionJNI.get_AUDIT_TIME_TAG();
  public final static String AUDIT_ACTION_TAG = affx_fusionJNI.get_AUDIT_ACTION_TAG();
  public final static String AUDIT_ARRAY_ID_TAG = affx_fusionJNI.get_AUDIT_ARRAY_ID_TAG();
  public final static String AUDIT_INPUT_ID_TAG = affx_fusionJNI.get_AUDIT_INPUT_ID_TAG();
  public final static String AUDIT_OUTPUT_ID_TAG = affx_fusionJNI.get_AUDIT_OUTPUT_ID_TAG();
  public final static String AUDIT_START_TAG = affx_fusionJNI.get_AUDIT_START_TAG();
  public final static String AUDIT_END_TAG = affx_fusionJNI.get_AUDIT_END_TAG();
  public final static String GRD_FILE_TYPE_IDENTIFIER = affx_fusionJNI.get_GRD_FILE_TYPE_IDENTIFIER();
  public final static String TEMPLATE_FILE_TYPE_IDENTIFIER = affx_fusionJNI.get_TEMPLATE_FILE_TYPE_IDENTIFIER();
  public final static int _AFFY_BASE_TYPE_H = affx_fusionJNI.get__AFFY_BASE_TYPE_H();
  public final static int __int8_t_defined = affx_fusionJNI.get___int8_t_defined();
  public final static int AFFX_FILEIO_H = affx_fusionJNI.get_AFFX_FILEIO_H();
  public final static int MAX_PROBE_SET_NAME_LENGTH = affx_fusionJNI.get_MAX_PROBE_SET_NAME_LENGTH();
  public final static int PROBE_SIZE = affx_fusionJNI.get_PROBE_SIZE();
  public final static int PROBE_GROUP_SIZE = affx_fusionJNI.get_PROBE_GROUP_SIZE();
  public final static int PROBE_SET_SIZE = affx_fusionJNI.get_PROBE_SET_SIZE();
  public final static int QC_PROBE_SIZE = affx_fusionJNI.get_QC_PROBE_SIZE();
  public final static int QC_PROBE_SET_SIZE = affx_fusionJNI.get_QC_PROBE_SET_SIZE();
  public final static int ABS_PRESENT_CALL = affx_fusionJNI.get_ABS_PRESENT_CALL();
  public final static int ABS_MARGINAL_CALL = affx_fusionJNI.get_ABS_MARGINAL_CALL();
  public final static int ABS_ABSENT_CALL = affx_fusionJNI.get_ABS_ABSENT_CALL();
  public final static int ABS_NO_CALL = affx_fusionJNI.get_ABS_NO_CALL();
  public final static int COMP_INCREASE_CALL = affx_fusionJNI.get_COMP_INCREASE_CALL();
  public final static int COMP_DECREASE_CALL = affx_fusionJNI.get_COMP_DECREASE_CALL();
  public final static int COMP_MOD_INCREASE_CALL = affx_fusionJNI.get_COMP_MOD_INCREASE_CALL();
  public final static int COMP_MOD_DECREASE_CALL = affx_fusionJNI.get_COMP_MOD_DECREASE_CALL();
  public final static int COMP_NO_CHANGE_CALL = affx_fusionJNI.get_COMP_NO_CHANGE_CALL();
  public final static int COMP_NO_CALL = affx_fusionJNI.get_COMP_NO_CALL();
  public final static int ALLELE_A_CALL = affx_fusionJNI.get_ALLELE_A_CALL();
  public final static int ALLELE_B_CALL = affx_fusionJNI.get_ALLELE_B_CALL();
  public final static int ALLELE_AB_CALL = affx_fusionJNI.get_ALLELE_AB_CALL();
  public final static int ALLELE_NO_CALL = affx_fusionJNI.get_ALLELE_NO_CALL();
  public final static char NO_SIGNAL_THR_FORCE_CALL = affx_fusionJNI.get_NO_SIGNAL_THR_FORCE_CALL();
  public final static char WEAK_SIGNAL_THR_FORCE_CALL = affx_fusionJNI.get_WEAK_SIGNAL_THR_FORCE_CALL();
  public final static char SATURATION_LEVEL_FORCE_CALL = affx_fusionJNI.get_SATURATION_LEVEL_FORCE_CALL();
  public final static char QUALITY_SCORE_THR_FORCE_CALL = affx_fusionJNI.get_QUALITY_SCORE_THR_FORCE_CALL();
  public final static char TRACE_AND_SEQUENCE_PROFILES_FORCE_CALL = affx_fusionJNI.get_TRACE_AND_SEQUENCE_PROFILES_FORCE_CALL();
  public final static char RELIABILITY_THR_FORCE_CALL = affx_fusionJNI.get_RELIABILITY_THR_FORCE_CALL();
  public final static String BPMAP_FILE_HEADER_BYTES = affx_fusionJNI.get_BPMAP_FILE_HEADER_BYTES();
  public final static int BPMAP_FILE_HEADER_LEN = affx_fusionJNI.get_BPMAP_FILE_HEADER_LEN();
  public final static int PM_ONLY = affx_fusionJNI.get_PM_ONLY();
  public final static int PM_MM = affx_fusionJNI.get_PM_MM();
  public final static int PROBE_STORAGE_BUFFER_LENGTH = affx_fusionJNI.get_PROBE_STORAGE_BUFFER_LENGTH();
  public final static int HIT_ITEM_SIZE_WITH_PROBE_PAIRS = affx_fusionJNI.get_HIT_ITEM_SIZE_WITH_PROBE_PAIRS();
  public final static int HIT_ITEM_SIZE_WITH_PM_ONLY = affx_fusionJNI.get_HIT_ITEM_SIZE_WITH_PM_ONLY();
  public final static int GRC_VERSION = affx_fusionJNI.get_GRC_VERSION();
  public final static int GRC_MAGIC = affx_fusionJNI.get_GRC_MAGIC();
  public final static String GCOS_SAMPLE_NAME_PARAMETER_NAME = affx_fusionJNI.get_GCOS_SAMPLE_NAME_PARAMETER_NAME();
  public final static String GCOS_SAMPLE_TYPE_PARAMETER_NAME = affx_fusionJNI.get_GCOS_SAMPLE_TYPE_PARAMETER_NAME();
  public final static String GCOS_SAMPLE_PROJECT_PARAMETER_NAME = affx_fusionJNI.get_GCOS_SAMPLE_PROJECT_PARAMETER_NAME();
}
