/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AffymetrixGuid {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AffymetrixGuid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AffymetrixGuid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_AffymetrixGuid(swigCPtr);
    }
    swigCPtr = 0;
  }

  public AffymetrixGuid() {
    this(affx_fusionJNI.new_AffymetrixGuid(), true);
  }

  public static String GenerateNewGuid() {
    return affx_fusionJNI.AffymetrixGuid_GenerateNewGuid();
  }

}
