/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ArrayFileReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ArrayFileReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayFileReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_ArrayFileReader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ArrayFileReader() {
    this(affx_fusionJNI.new_ArrayFileReader(), true);
  }

  public boolean Read(String fileName, ArrayData arrayData, boolean headerOnly) {
    return affx_fusionJNI.ArrayFileReader_Read__SWIG_0(swigCPtr, fileName, ArrayData.getCPtr(arrayData), headerOnly);
  }

  public boolean Read(String fileName, ArrayData arrayData) {
    return affx_fusionJNI.ArrayFileReader_Read__SWIG_1(swigCPtr, fileName, ArrayData.getCPtr(arrayData));
  }

  public String DataTypeIdentifier() {
    return affx_fusionJNI.ArrayFileReader_DataTypeIdentifier__SWIG_0(swigCPtr);
  }

  public static boolean IsFileType(String fileName, String dataTypeId) {
    return affx_fusionJNI.ArrayFileReader_IsFileType(fileName, dataTypeId);
  }

  public static String DataTypeIdentifier(String fileName) {
    return affx_fusionJNI.ArrayFileReader_DataTypeIdentifier__SWIG_1(fileName);
  }

}
