/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ArrayData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ArrayData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_ArrayData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ArrayData() {
    this(affx_fusionJNI.new_ArrayData(), true);
  }

  public SWIGTYPE_p_std__string ArraySetIdentifier() {
    return new SWIGTYPE_p_std__string(affx_fusionJNI.ArrayData_ArraySetIdentifier(swigCPtr), false);
  }

  public SWIGTYPE_p_std__vectorTaffymetrix_calvin_array__ArrayAttributes_t PhysicalArraysAttributes() {
    return new SWIGTYPE_p_std__vectorTaffymetrix_calvin_array__ArrayAttributes_t(affx_fusionJNI.ArrayData_PhysicalArraysAttributes(swigCPtr), false);
  }

  public SWIGTYPE_p_std__vectorTaffymetrix_calvin_parameter___tagParameterNameValueControlVocabulary_t UserAttributes() {
    return new SWIGTYPE_p_std__vectorTaffymetrix_calvin_parameter___tagParameterNameValueControlVocabulary_t(affx_fusionJNI.ArrayData_UserAttributes(swigCPtr), false);
  }

  public void Clear() {
    affx_fusionJNI.ArrayData_Clear(swigCPtr);
  }

}
