/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AttributeNameValueType {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AttributeNameValueType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttributeNameValueType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_AttributeNameValueType(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setName(SWIGTYPE_p_std__string value) {
    affx_fusionJNI.set_AttributeNameValueType_name(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getName() {
    long cPtr = affx_fusionJNI.get_AttributeNameValueType_name(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void setValue(SWIGTYPE_p_std__string value) {
    affx_fusionJNI.set_AttributeNameValueType_value(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getValue() {
    long cPtr = affx_fusionJNI.get_AttributeNameValueType_value(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void setType(SWIGTYPE_p_std__string value) {
    affx_fusionJNI.set_AttributeNameValueType_type(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getType() {
    long cPtr = affx_fusionJNI.get_AttributeNameValueType_type(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public AttributeNameValueType() {
    this(affx_fusionJNI.new_AttributeNameValueType(), true);
  }

}
