/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class BaseCallType {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BaseCallType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BaseCallType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_BaseCallType(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setPosition(int value) {
    affx_fusionJNI.set_BaseCallType_position(swigCPtr, value);
  }

  public int getPosition() {
    return affx_fusionJNI.get_BaseCallType_position(swigCPtr);
  }

  public void setCall(char value) {
    affx_fusionJNI.set_BaseCallType_call(swigCPtr, value);
  }

  public char getCall() {
    return affx_fusionJNI.get_BaseCallType_call(swigCPtr);
  }

  public BaseCallType() {
    this(affx_fusionJNI.new_BaseCallType(), true);
  }

}
