/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CalvinException {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CalvinException(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CalvinException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CalvinException(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CalvinException() {
    this(affx_fusionJNI.new_CalvinException__SWIG_0(), true);
  }

  public CalvinException(SWIGTYPE_p_std__wstring _Source, SWIGTYPE_p_std__wstring _Description, SWIGTYPE_p_std__wstring _TimeStamp, String _FileName, int _LineNumber, java.math.BigInteger _ErrorCode) {
    this(affx_fusionJNI.new_CalvinException__SWIG_1(SWIGTYPE_p_std__wstring.getCPtr(_Source), SWIGTYPE_p_std__wstring.getCPtr(_Description), SWIGTYPE_p_std__wstring.getCPtr(_TimeStamp), _FileName, _LineNumber, _ErrorCode), true);
  }

  public CalvinException(SWIGTYPE_p_std__wstring _Source, SWIGTYPE_p_std__wstring _Description, java.math.BigInteger _ErrorCode) {
    this(affx_fusionJNI.new_CalvinException__SWIG_2(SWIGTYPE_p_std__wstring.getCPtr(_Source), SWIGTYPE_p_std__wstring.getCPtr(_Description), _ErrorCode), true);
  }

  public CalvinException(SWIGTYPE_p_std__wstring _Description, java.math.BigInteger _ErrorCode) {
    this(affx_fusionJNI.new_CalvinException__SWIG_3(SWIGTYPE_p_std__wstring.getCPtr(_Description), _ErrorCode), true);
  }

  public CalvinException(java.math.BigInteger _ErrorCode) {
    this(affx_fusionJNI.new_CalvinException__SWIG_4(_ErrorCode), true);
  }

  public SWIGTYPE_p_std__wstring Source() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.CalvinException_Source__SWIG_0(swigCPtr), true);
  }

  public void Source(SWIGTYPE_p_std__wstring value) {
    affx_fusionJNI.CalvinException_Source__SWIG_1(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring Description() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.CalvinException_Description__SWIG_0(swigCPtr), true);
  }

  public void Description(SWIGTYPE_p_std__wstring value) {
    affx_fusionJNI.CalvinException_Description__SWIG_1(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring TimeStamp() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.CalvinException_TimeStamp__SWIG_0(swigCPtr), true);
  }

  public void TimeStamp(SWIGTYPE_p_std__wstring value) {
    affx_fusionJNI.CalvinException_TimeStamp__SWIG_1(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public String SourceFile() {
    return affx_fusionJNI.CalvinException_SourceFile__SWIG_0(swigCPtr);
  }

  public void SourceFile(String value) {
    affx_fusionJNI.CalvinException_SourceFile__SWIG_1(swigCPtr, value);
  }

  public int LineNumber() {
    return affx_fusionJNI.CalvinException_LineNumber__SWIG_0(swigCPtr);
  }

  public void LineNumber(int value) {
    affx_fusionJNI.CalvinException_LineNumber__SWIG_1(swigCPtr, value);
  }

  public java.math.BigInteger ErrorCode() {
    return affx_fusionJNI.CalvinException_ErrorCode__SWIG_0(swigCPtr);
  }

  public void ErrorCode(java.math.BigInteger value) {
    affx_fusionJNI.CalvinException_ErrorCode__SWIG_1(swigCPtr, value);
  }

  public SWIGTYPE_p_std__wstring ToString() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.CalvinException_ToString(swigCPtr), true);
  }

}
