/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CBARFileData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CBARFileData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CBARFileData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CBARFileData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CBARFileData() {
    this(affx_fusionJNI.new_CBARFileData(), true);
  }

  public void SetFileName(String name) {
    affx_fusionJNI.CBARFileData_SetFileName(swigCPtr, name);
  }

  public String GetFileName() {
    return affx_fusionJNI.CBARFileData_GetFileName(swigCPtr);
  }

  public boolean Read() {
    return affx_fusionJNI.CBARFileData_Read(swigCPtr);
  }

  public boolean ReadHeader() {
    return affx_fusionJNI.CBARFileData_ReadHeader(swigCPtr);
  }

  public boolean Exists() {
    return affx_fusionJNI.CBARFileData_Exists(swigCPtr);
  }

  public void Close() {
    affx_fusionJNI.CBARFileData_Close(swigCPtr);
  }

  public String GetError() {
    return affx_fusionJNI.CBARFileData_GetError(swigCPtr);
  }

  public float GetVersion() {
    return affx_fusionJNI.CBARFileData_GetVersion(swigCPtr);
  }

  public int GetNumberSequences() {
    return affx_fusionJNI.CBARFileData_GetNumberSequences(swigCPtr);
  }

  public int GetNumberColumns() {
    return affx_fusionJNI.CBARFileData_GetNumberColumns(swigCPtr);
  }

  public int GetNumberParameters() {
    return affx_fusionJNI.CBARFileData_GetNumberParameters(swigCPtr);
  }

  public TagValuePairType GetParameter(int index) {
    return new TagValuePairType(affx_fusionJNI.CBARFileData_GetParameter(swigCPtr, index), false);
  }

  public SWIGTYPE_p_affxbar___GDACFILES_BAR_DATA_TYPE GetColumnTypes(int index) {
    return new SWIGTYPE_p_affxbar___GDACFILES_BAR_DATA_TYPE(affx_fusionJNI.CBARFileData_GetColumnTypes(swigCPtr, index), false);
  }

  public void GetResults(int index, CGDACSequenceResultItem seq) {
    affx_fusionJNI.CBARFileData_GetResults(swigCPtr, index, CGDACSequenceResultItem.getCPtr(seq));
  }

  public void AddAlgorithmParameter(String tag, String value) {
    affx_fusionJNI.CBARFileData_AddAlgorithmParameter(swigCPtr, tag, value);
  }

  public void AddColumn(GDACFILES_BAR_DATA_TYPE ctype) {
    affx_fusionJNI.CBARFileData_AddColumn(swigCPtr, ctype.swigValue());
  }

  public void SetNumberSequences(int n) {
    affx_fusionJNI.CBARFileData_SetNumberSequences(swigCPtr, n);
  }

  public CGDACSequenceResultItem GetResultsPtr(int index) {
    long cPtr = affx_fusionJNI.CBARFileData_GetResultsPtr(swigCPtr, index);
    return (cPtr == 0) ? null : new CGDACSequenceResultItem(cPtr, false);
  }

}
