/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CBPMAPFileData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CBPMAPFileData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CBPMAPFileData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CBPMAPFileData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CBPMAPFileData() {
    this(affx_fusionJNI.new_CBPMAPFileData(), true);
  }

  public void SetFileName(String name) {
    affx_fusionJNI.CBPMAPFileData_SetFileName(swigCPtr, name);
  }

  public String GetFileName() {
    return affx_fusionJNI.CBPMAPFileData_GetFileName(swigCPtr);
  }

  public boolean Read() {
    return affx_fusionJNI.CBPMAPFileData_Read(swigCPtr);
  }

  public boolean ReadHeader() {
    return affx_fusionJNI.CBPMAPFileData_ReadHeader(swigCPtr);
  }

  public boolean Exists() {
    return affx_fusionJNI.CBPMAPFileData_Exists(swigCPtr);
  }

  public void Close() {
    affx_fusionJNI.CBPMAPFileData_Close(swigCPtr);
  }

  public String GetError() {
    return affx_fusionJNI.CBPMAPFileData_GetError(swigCPtr);
  }

  public int GetNumberSequences() {
    return affx_fusionJNI.CBPMAPFileData_GetNumberSequences(swigCPtr);
  }

  public float GetVersion() {
    return affx_fusionJNI.CBPMAPFileData_GetVersion(swigCPtr);
  }

  public void GetSequenceItem(int index, CGDACSequenceItem seq) {
    affx_fusionJNI.CBPMAPFileData_GetSequenceItem(swigCPtr, index, CGDACSequenceItem.getCPtr(seq));
  }

}
