/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCDFProbeSetNames {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCDFProbeSetNames(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCDFProbeSetNames obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CCDFProbeSetNames(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CCDFProbeSetNames() {
    this(affx_fusionJNI.new_CCDFProbeSetNames(), true);
  }

  public void Clear() {
    affx_fusionJNI.CCDFProbeSetNames_Clear(swigCPtr);
  }

  public String GetName(int index) {
    return affx_fusionJNI.CCDFProbeSetNames_GetName(swigCPtr, index);
  }

}
