/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCDFFileHeader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCDFFileHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCDFFileHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CCDFFileHeader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public int GetCols() {
    return affx_fusionJNI.CCDFFileHeader_GetCols(swigCPtr);
  }

  public int GetRows() {
    return affx_fusionJNI.CCDFFileHeader_GetRows(swigCPtr);
  }

  public int GetNumProbeSets() {
    return affx_fusionJNI.CCDFFileHeader_GetNumProbeSets(swigCPtr);
  }

  public int GetNumQCProbeSets() {
    return affx_fusionJNI.CCDFFileHeader_GetNumQCProbeSets(swigCPtr);
  }

  public SWIGTYPE_p_std__string GetReference() {
    return new SWIGTYPE_p_std__string(affx_fusionJNI.CCDFFileHeader_GetReference(swigCPtr), false);
  }

  public CCDFFileHeader() {
    this(affx_fusionJNI.new_CCDFFileHeader(), true);
  }

}
