/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCDFQCProbeSetInformation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCDFQCProbeSetInformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCDFQCProbeSetInformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CCDFQCProbeSetInformation(swigCPtr);
    }
    swigCPtr = 0;
  }

  public GeneChipQCProbeSetType GetQCProbeSetType() {
    return GeneChipQCProbeSetType.swigToEnum(affx_fusionJNI.CCDFQCProbeSetInformation_GetQCProbeSetType(swigCPtr));
  }

  public int GetNumCells() {
    return affx_fusionJNI.CCDFQCProbeSetInformation_GetNumCells(swigCPtr);
  }

  public void GetProbeInformation(int index, CCDFQCProbeInformation info) {
    affx_fusionJNI.CCDFQCProbeSetInformation_GetProbeInformation(swigCPtr, index, CCDFQCProbeInformation.getCPtr(info));
  }

  public CCDFQCProbeSetInformation() {
    this(affx_fusionJNI.new_CCDFQCProbeSetInformation(), true);
  }

}
