/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCDFProbeGroupInformation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCDFProbeGroupInformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCDFProbeGroupInformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CCDFProbeGroupInformation(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DirectionType GetDirection() {
    return DirectionType.swigToEnum(affx_fusionJNI.CCDFProbeGroupInformation_GetDirection(swigCPtr));
  }

  public int GetNumLists() {
    return affx_fusionJNI.CCDFProbeGroupInformation_GetNumLists(swigCPtr);
  }

  public int GetNumCells() {
    return affx_fusionJNI.CCDFProbeGroupInformation_GetNumCells(swigCPtr);
  }

  public int GetNumCellsPerList() {
    return affx_fusionJNI.CCDFProbeGroupInformation_GetNumCellsPerList(swigCPtr);
  }

  public int GetStart() {
    return affx_fusionJNI.CCDFProbeGroupInformation_GetStart(swigCPtr);
  }

  public int GetStop() {
    return affx_fusionJNI.CCDFProbeGroupInformation_GetStop(swigCPtr);
  }

  public String GetName() {
    return affx_fusionJNI.CCDFProbeGroupInformation_GetName(swigCPtr);
  }

  public void GetCell(int cell_index, CCDFProbeInformation info) {
    affx_fusionJNI.CCDFProbeGroupInformation_GetCell(swigCPtr, cell_index, CCDFProbeInformation.getCPtr(info));
  }

  public CCDFProbeGroupInformation() {
    this(affx_fusionJNI.new_CCDFProbeGroupInformation(), true);
  }

}
