/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCELFileHeaderData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCELFileHeaderData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCELFileHeaderData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CCELFileHeaderData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CCELFileHeaderData() {
    this(affx_fusionJNI.new_CCELFileHeaderData(), true);
  }

  public void Clear() {
    affx_fusionJNI.CCELFileHeaderData_Clear(swigCPtr);
  }

  public void SetMagic(int i) {
    affx_fusionJNI.CCELFileHeaderData_SetMagic(swigCPtr, i);
  }

  public int GetMagic() {
    return affx_fusionJNI.CCELFileHeaderData_GetMagic(swigCPtr);
  }

  public void SetVersion(int i) {
    affx_fusionJNI.CCELFileHeaderData_SetVersion(swigCPtr, i);
  }

  public int GetVersion() {
    return affx_fusionJNI.CCELFileHeaderData_GetVersion(swigCPtr);
  }

  public void SetCols(int i) {
    affx_fusionJNI.CCELFileHeaderData_SetCols(swigCPtr, i);
  }

  public int GetCols() {
    return affx_fusionJNI.CCELFileHeaderData_GetCols(swigCPtr);
  }

  public void SetRows(int i) {
    affx_fusionJNI.CCELFileHeaderData_SetRows(swigCPtr, i);
  }

  public int GetRows() {
    return affx_fusionJNI.CCELFileHeaderData_GetRows(swigCPtr);
  }

  public void SetCells(int i) {
    affx_fusionJNI.CCELFileHeaderData_SetCells(swigCPtr, i);
  }

  public int GetCells() {
    return affx_fusionJNI.CCELFileHeaderData_GetCells(swigCPtr);
  }

  public void AppendHeader(String p) {
    affx_fusionJNI.CCELFileHeaderData_AppendHeader(swigCPtr, p);
  }

  public void SetHeader(String p) {
    affx_fusionJNI.CCELFileHeaderData_SetHeader(swigCPtr, p);
  }

  public String GetHeader() {
    return affx_fusionJNI.CCELFileHeaderData_GetHeader(swigCPtr);
  }

  public void SetAlg(String p) {
    affx_fusionJNI.CCELFileHeaderData_SetAlg(swigCPtr, p);
  }

  public String GetAlg() {
    return affx_fusionJNI.CCELFileHeaderData_GetAlg(swigCPtr);
  }

  public void SetParams(String p) {
    affx_fusionJNI.CCELFileHeaderData_SetParams(swigCPtr, p);
  }

  public String GetParams() {
    return affx_fusionJNI.CCELFileHeaderData_GetParams(swigCPtr);
  }

  public void ParseChipType() {
    affx_fusionJNI.CCELFileHeaderData_ParseChipType(swigCPtr);
  }

  public void SetChipType(String p) {
    affx_fusionJNI.CCELFileHeaderData_SetChipType(swigCPtr, p);
  }

  public String GetChipType() {
    return affx_fusionJNI.CCELFileHeaderData_GetChipType(swigCPtr);
  }

  public void ParseDatHeader() {
    affx_fusionJNI.CCELFileHeaderData_ParseDatHeader(swigCPtr);
  }

  public void SetDatHeader() {
    affx_fusionJNI.CCELFileHeaderData_SetDatHeader__SWIG_0(swigCPtr);
  }

  public void SetDatHeader(String p) {
    affx_fusionJNI.CCELFileHeaderData_SetDatHeader__SWIG_1(swigCPtr, p);
  }

  public String GetDatHeader() {
    return affx_fusionJNI.CCELFileHeaderData_GetDatHeader(swigCPtr);
  }

  public void SetMargin(int i) {
    affx_fusionJNI.CCELFileHeaderData_SetMargin(swigCPtr, i);
  }

  public int GetMargin() {
    return affx_fusionJNI.CCELFileHeaderData_GetMargin(swigCPtr);
  }

  public void SetOutliers(long l) {
    affx_fusionJNI.CCELFileHeaderData_SetOutliers(swigCPtr, l);
  }

  public long GetOutliers() {
    return affx_fusionJNI.CCELFileHeaderData_GetOutliers(swigCPtr);
  }

  public void IncrementOutliers() {
    affx_fusionJNI.CCELFileHeaderData_IncrementOutliers(swigCPtr);
  }

  public void DecrementOutliers() {
    affx_fusionJNI.CCELFileHeaderData_DecrementOutliers(swigCPtr);
  }

  public void SetMasked(long l) {
    affx_fusionJNI.CCELFileHeaderData_SetMasked(swigCPtr, l);
  }

  public long GetMasked() {
    return affx_fusionJNI.CCELFileHeaderData_GetMasked(swigCPtr);
  }

  public void IncrementMasked() {
    affx_fusionJNI.CCELFileHeaderData_IncrementMasked(swigCPtr);
  }

  public void DecrementMasked() {
    affx_fusionJNI.CCELFileHeaderData_DecrementMasked(swigCPtr);
  }

  public void ParseAlgorithmParameters() {
    affx_fusionJNI.CCELFileHeaderData_ParseAlgorithmParameters(swigCPtr);
  }

  public void AddAlgorithmParameter(SWIGTYPE_p_std__string tag, SWIGTYPE_p_std__string value) {
    affx_fusionJNI.CCELFileHeaderData_AddAlgorithmParameter__SWIG_0(swigCPtr, SWIGTYPE_p_std__string.getCPtr(tag), SWIGTYPE_p_std__string.getCPtr(value));
  }

  public void AddAlgorithmParameter(String tag, String value) {
    affx_fusionJNI.CCELFileHeaderData_AddAlgorithmParameter__SWIG_1(swigCPtr, tag, value);
  }

  public void SetAlgorithmParameter(String tag, String value) {
    affx_fusionJNI.CCELFileHeaderData_SetAlgorithmParameter(swigCPtr, tag, value);
  }

  public String GetAlgorithmParameter(String tag) {
    return affx_fusionJNI.CCELFileHeaderData_GetAlgorithmParameter(swigCPtr, tag);
  }

  public String GetAlgorithmParameterTag(int index) {
    return affx_fusionJNI.CCELFileHeaderData_GetAlgorithmParameterTag(swigCPtr, index);
  }

  public int GetNumberAlgorithmParameters() {
    return affx_fusionJNI.CCELFileHeaderData_GetNumberAlgorithmParameters(swigCPtr);
  }

  public String GetAlgorithmParameters() {
    return affx_fusionJNI.CCELFileHeaderData_GetAlgorithmParameters(swigCPtr);
  }

  public void SetGridCorners(GridCoordinatesType grid) {
    affx_fusionJNI.CCELFileHeaderData_SetGridCorners(swigCPtr, GridCoordinatesType.getCPtr(grid));
  }

  public void ParseCorners() {
    affx_fusionJNI.CCELFileHeaderData_ParseCorners(swigCPtr);
  }

  public GridCoordinatesType GetGridCorners() {
    return new GridCoordinatesType(affx_fusionJNI.CCELFileHeaderData_GetGridCorners(swigCPtr), true);
  }

}
