/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CDFQCProbeSetInformation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CDFQCProbeSetInformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CDFQCProbeSetInformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CDFQCProbeSetInformation(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CDFQCProbeSetInformation() {
    this(affx_fusionJNI.new_CDFQCProbeSetInformation(), true);
  }

  public SWIGTYPE_p_std__wstring GetQCProbeSetType() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.CDFQCProbeSetInformation_GetQCProbeSetType(swigCPtr), true);
  }

  public int GetNumCells() {
    return affx_fusionJNI.CDFQCProbeSetInformation_GetNumCells(swigCPtr);
  }

  public void GetProbeInformation(int index, CDFQCProbeInformation info) {
    affx_fusionJNI.CDFQCProbeSetInformation_GetProbeInformation(swigCPtr, index, CDFQCProbeInformation.getCPtr(info));
  }

}
