/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CelFileReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CelFileReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CelFileReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CelFileReader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CelFileReader() {
    this(affx_fusionJNI.new_CelFileReader(), true);
  }

  public String GetFilename() {
    return affx_fusionJNI.CelFileReader_GetFilename(swigCPtr);
  }

  public void SetFilename(String name) {
    affx_fusionJNI.CelFileReader_SetFilename(swigCPtr, name);
  }

  public void Read(CelFileData data) {
    affx_fusionJNI.CelFileReader_Read(swigCPtr, CelFileData.getCPtr(data));
  }

}
