/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CGDACSequenceResultItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CGDACSequenceResultItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CGDACSequenceResultItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CGDACSequenceResultItem(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CGDACSequenceResultItem() {
    this(affx_fusionJNI.new_CGDACSequenceResultItem(), true);
  }

  public String GetName() {
    return affx_fusionJNI.CGDACSequenceResultItem_GetName(swigCPtr);
  }

  public String GetVersion() {
    return affx_fusionJNI.CGDACSequenceResultItem_GetVersion(swigCPtr);
  }

  public String GetGroupName() {
    return affx_fusionJNI.CGDACSequenceResultItem_GetGroupName(swigCPtr);
  }

  public int GetNumberDataPoints() {
    return affx_fusionJNI.CGDACSequenceResultItem_GetNumberDataPoints(swigCPtr);
  }

  public int GetNumberColumns() {
    return affx_fusionJNI.CGDACSequenceResultItem_GetNumberColumns(swigCPtr);
  }

  public GDACFILES_BAR_DATA_TYPE GetColumnType(int index) {
    return GDACFILES_BAR_DATA_TYPE.swigToEnum(affx_fusionJNI.CGDACSequenceResultItem_GetColumnType(swigCPtr, index));
  }

  public void GetData(int iData, int iCol, BarSequenceResultData data) {
    affx_fusionJNI.CGDACSequenceResultItem_GetData(swigCPtr, iData, iCol, BarSequenceResultData.getCPtr(data));
  }

  public int GetNumberParameters() {
    return affx_fusionJNI.CGDACSequenceResultItem_GetNumberParameters(swigCPtr);
  }

  public TagValuePairType GetParameter(int index) {
    return new TagValuePairType(affx_fusionJNI.CGDACSequenceResultItem_GetParameter(swigCPtr, index), false);
  }

  public void SetName(String name) {
    affx_fusionJNI.CGDACSequenceResultItem_SetName(swigCPtr, name);
  }

  public void SetVersion(String ver) {
    affx_fusionJNI.CGDACSequenceResultItem_SetVersion(swigCPtr, ver);
  }

  public void SetGroupName(String group) {
    affx_fusionJNI.CGDACSequenceResultItem_SetGroupName(swigCPtr, group);
  }

  public void SetNumberDataPoints(int n) {
    affx_fusionJNI.CGDACSequenceResultItem_SetNumberDataPoints(swigCPtr, n);
  }

  public void SetDataPoint(int nIndex, int colIndex, BarSequenceResultData data) {
    affx_fusionJNI.CGDACSequenceResultItem_SetDataPoint(swigCPtr, nIndex, colIndex, BarSequenceResultData.getCPtr(data));
  }

  public void AddParameter(String tag, String value) {
    affx_fusionJNI.CGDACSequenceResultItem_AddParameter(swigCPtr, tag, value);
  }

}
