/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CheckSum {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CheckSum(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CheckSum obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CheckSum(swigCPtr);
    }
    swigCPtr = 0;
  }

  public static int OnesComplementCheckSum(SWIGTYPE_p_void addr, long size) {
    return affx_fusionJNI.CheckSum_OnesComplementCheckSum(SWIGTYPE_p_void.getCPtr(addr), size);
  }

  public CheckSum() {
    this(affx_fusionJNI.new_CheckSum(), true);
  }

}
