/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CHPGenotypeEntry {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CHPGenotypeEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CHPGenotypeEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CHPGenotypeEntry(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CHPGenotypeEntry() {
    this(affx_fusionJNI.new_CHPGenotypeEntry__SWIG_0(), true);
  }

  public CHPGenotypeEntry(SWIGTYPE_p_std__wstring probeSetname, short call, float confidence, float RAS1, float RAS2, float AACall, float ABCall, float BBCall, float NoCall) {
    this(affx_fusionJNI.new_CHPGenotypeEntry__SWIG_1(SWIGTYPE_p_std__wstring.getCPtr(probeSetname), call, confidence, RAS1, RAS2, AACall, ABCall, BBCall, NoCall), true);
  }

  public void Clear() {
    affx_fusionJNI.CHPGenotypeEntry_Clear(swigCPtr);
  }

  public CHPGenotypeEntry CHPGenotypeEntry_assign(CHPGenotypeEntry zn) {
    return new CHPGenotypeEntry(affx_fusionJNI.CHPGenotypeEntry_CHPGenotypeEntry_assign(swigCPtr, CHPGenotypeEntry.getCPtr(zn)), true);
  }

  public SWIGTYPE_p_std__wstring GetProbeSetName() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.CHPGenotypeEntry_GetProbeSetName(swigCPtr), true);
  }

  public short GetCall() {
    return affx_fusionJNI.CHPGenotypeEntry_GetCall(swigCPtr);
  }

  public float GetConfidence() {
    return affx_fusionJNI.CHPGenotypeEntry_GetConfidence(swigCPtr);
  }

  public float GetRAS1() {
    return affx_fusionJNI.CHPGenotypeEntry_GetRAS1(swigCPtr);
  }

  public float GetRAS2() {
    return affx_fusionJNI.CHPGenotypeEntry_GetRAS2(swigCPtr);
  }

  public float GetAACall() {
    return affx_fusionJNI.CHPGenotypeEntry_GetAACall(swigCPtr);
  }

  public float GetABCall() {
    return affx_fusionJNI.CHPGenotypeEntry_GetABCall(swigCPtr);
  }

  public float GetBBCall() {
    return affx_fusionJNI.CHPGenotypeEntry_GetBBCall(swigCPtr);
  }

  public float GetNoCall() {
    return affx_fusionJNI.CHPGenotypeEntry_GetNoCall(swigCPtr);
  }

  public void SetProbeSetName(SWIGTYPE_p_std__wstring p) {
    affx_fusionJNI.CHPGenotypeEntry_SetProbeSetName(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(p));
  }

  public void SetCall(short p) {
    affx_fusionJNI.CHPGenotypeEntry_SetCall(swigCPtr, p);
  }

  public void SetConfidence(float p) {
    affx_fusionJNI.CHPGenotypeEntry_SetConfidence(swigCPtr, p);
  }

  public void SetRAS1(float p) {
    affx_fusionJNI.CHPGenotypeEntry_SetRAS1(swigCPtr, p);
  }

  public void SetRAS2(float p) {
    affx_fusionJNI.CHPGenotypeEntry_SetRAS2(swigCPtr, p);
  }

  public void SetAACall(float p) {
    affx_fusionJNI.CHPGenotypeEntry_SetAACall(swigCPtr, p);
  }

  public void SetABCall(float p) {
    affx_fusionJNI.CHPGenotypeEntry_SetABCall(swigCPtr, p);
  }

  public void SetBBCall(float p) {
    affx_fusionJNI.CHPGenotypeEntry_SetBBCall(swigCPtr, p);
  }

  public void SetNoCall(float p) {
    affx_fusionJNI.CHPGenotypeEntry_SetNoCall(swigCPtr, p);
  }

}
