/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CMSKFileData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CMSKFileData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CMSKFileData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CMSKFileData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CMSKFileData() {
    this(affx_fusionJNI.new_CMSKFileData(), true);
  }

  public void SetFileName(String name) {
    affx_fusionJNI.CMSKFileData_SetFileName(swigCPtr, name);
  }

  public String GetFileName() {
    return affx_fusionJNI.CMSKFileData_GetFileName(swigCPtr);
  }

  public String GetArrayType() {
    return affx_fusionJNI.CMSKFileData_GetArrayType(swigCPtr);
  }

  public int GetProbeSetIndiciesListCount() {
    return affx_fusionJNI.CMSKFileData_GetProbeSetIndiciesListCount(swigCPtr);
  }

  public int GetProbeSetListCount() {
    return affx_fusionJNI.CMSKFileData_GetProbeSetListCount(swigCPtr);
  }

  public String GetError() {
    return affx_fusionJNI.CMSKFileData_GetError(swigCPtr);
  }

  public void GetProbeSetIndiciesIterators(SWIGTYPE_p_affxmsk__ProbeSetIndiciesList__const_iterator begin, SWIGTYPE_p_affxmsk__ProbeSetIndiciesList__const_iterator end) {
    affx_fusionJNI.CMSKFileData_GetProbeSetIndiciesIterators(swigCPtr, SWIGTYPE_p_affxmsk__ProbeSetIndiciesList__const_iterator.getCPtr(begin), SWIGTYPE_p_affxmsk__ProbeSetIndiciesList__const_iterator.getCPtr(end));
  }

  public void GetProbeSetIterators(SWIGTYPE_p_affxmsk__ProbeSetList__const_iterator begin, SWIGTYPE_p_affxmsk__ProbeSetList__const_iterator end) {
    affx_fusionJNI.CMSKFileData_GetProbeSetIterators(swigCPtr, SWIGTYPE_p_affxmsk__ProbeSetList__const_iterator.getCPtr(begin), SWIGTYPE_p_affxmsk__ProbeSetList__const_iterator.getCPtr(end));
  }

  public boolean Read() {
    return affx_fusionJNI.CMSKFileData_Read(swigCPtr);
  }

  public boolean Exists() {
    return affx_fusionJNI.CMSKFileData_Exists(swigCPtr);
  }

  public void Clear() {
    affx_fusionJNI.CMSKFileData_Clear(swigCPtr);
  }

}
