/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ColumnType {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ColumnType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColumnType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_ColumnType(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ColumnType(DataSetColumnTypes type_, int totalSize) {
    this(affx_fusionJNI.new_ColumnType(type_.swigValue(), totalSize), true);
  }

  public boolean ColumnType_equals(ColumnType p) {
    return affx_fusionJNI.ColumnType_ColumnType_equals(swigCPtr, ColumnType.getCPtr(p));
  }

  public boolean ColumnType_not_equals(ColumnType p) {
    return affx_fusionJNI.ColumnType_ColumnType_not_equals(swigCPtr, ColumnType.getCPtr(p));
  }

  public DataSetColumnTypes GetColumnType() {
    return DataSetColumnTypes.swigToEnum(affx_fusionJNI.ColumnType_GetColumnType(swigCPtr));
  }

  public int GetSize() {
    return affx_fusionJNI.ColumnType_GetSize(swigCPtr);
  }

  public int GetLength() {
    return affx_fusionJNI.ColumnType_GetLength(swigCPtr);
  }

}
