/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CoordinatePoint {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CoordinatePoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CoordinatePoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CoordinatePoint(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setX(int value) {
    affx_fusionJNI.set_CoordinatePoint_x(swigCPtr, value);
  }

  public int getX() {
    return affx_fusionJNI.get_CoordinatePoint_x(swigCPtr);
  }

  public void setY(int value) {
    affx_fusionJNI.set_CoordinatePoint_y(swigCPtr, value);
  }

  public int getY() {
    return affx_fusionJNI.get_CoordinatePoint_y(swigCPtr);
  }

  public CoordinatePoint() {
    this(affx_fusionJNI.new_CoordinatePoint(), true);
  }

}
