/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CPSIFileData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CPSIFileData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CPSIFileData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CPSIFileData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CPSIFileData() {
    this(affx_fusionJNI.new_CPSIFileData(), true);
  }

  public void SetFileName(String name) {
    affx_fusionJNI.CPSIFileData_SetFileName(swigCPtr, name);
  }

  public String GetFileName() {
    return affx_fusionJNI.CPSIFileData_GetFileName(swigCPtr);
  }

  public int GetProbeSetCount() {
    return affx_fusionJNI.CPSIFileData_GetProbeSetCount(swigCPtr);
  }

  public String GetProbeSetName(int index) {
    return affx_fusionJNI.CPSIFileData_GetProbeSetName(swigCPtr, index);
  }

  public int GetProbePairs(int index) {
    return affx_fusionJNI.CPSIFileData_GetProbePairs(swigCPtr, index);
  }

  public boolean Read() {
    return affx_fusionJNI.CPSIFileData_Read(swigCPtr);
  }

  public boolean Exists() {
    return affx_fusionJNI.CPSIFileData_Exists(swigCPtr);
  }

  public void Clear() {
    affx_fusionJNI.CPSIFileData_Clear(swigCPtr);
  }

}
