/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CUniversalProbeSetResults extends CProbeSetResults {
  private long swigCPtr;

  protected CUniversalProbeSetResults(long cPtr, boolean cMemoryOwn) {
    super(affx_fusionJNI.SWIGCUniversalProbeSetResultsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CUniversalProbeSetResults obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_CUniversalProbeSetResults(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public float GetBackground() {
    return affx_fusionJNI.CUniversalProbeSetResults_GetBackground(swigCPtr);
  }

  public void SetBackground(float bg) {
    affx_fusionJNI.CUniversalProbeSetResults_SetBackground(swigCPtr, bg);
  }

  public CUniversalProbeSetResults CUniversalProbeSetResults_assign(CUniversalProbeSetResults src) {
    return new CUniversalProbeSetResults(affx_fusionJNI.CUniversalProbeSetResults_CUniversalProbeSetResults_assign(swigCPtr, CUniversalProbeSetResults.getCPtr(src)), true);
  }

  public CUniversalProbeSetResults() {
    this(affx_fusionJNI.new_CUniversalProbeSetResults(), true);
  }

}
