/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DataGroupHeader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataGroupHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataGroupHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_DataGroupHeader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DataGroupHeader() {
    this(affx_fusionJNI.new_DataGroupHeader__SWIG_0(), true);
  }

  public DataGroupHeader(SWIGTYPE_p_std__wstring n) {
    this(affx_fusionJNI.new_DataGroupHeader__SWIG_1(SWIGTYPE_p_std__wstring.getCPtr(n)), true);
  }

  public void Clear() {
    affx_fusionJNI.DataGroupHeader_Clear(swigCPtr);
  }

  public void SetName(SWIGTYPE_p_std__wstring p) {
    affx_fusionJNI.DataGroupHeader_SetName(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(p));
  }

  public SWIGTYPE_p_std__wstring GetName() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.DataGroupHeader_GetName(swigCPtr), true);
  }

  public int GetDataSetCnt() {
    return affx_fusionJNI.DataGroupHeader_GetDataSetCnt(swigCPtr);
  }

  public void AddDataSetHdr(DataSetHeader p) {
    affx_fusionJNI.DataGroupHeader_AddDataSetHdr(swigCPtr, DataSetHeader.getCPtr(p));
  }

  public DataSetHeader GetDataSet(int index) {
    return new DataSetHeader(affx_fusionJNI.DataGroupHeader_GetDataSet(swigCPtr, index), false);
  }

  public DataSetHeader GetDataSetConst(int index) {
    return new DataSetHeader(affx_fusionJNI.DataGroupHeader_GetDataSetConst(swigCPtr, index), false);
  }

  public void GetDataSetIterators(SWIGTYPE_p_std__vectorTaffymetrix_calvin_io__DataSetHeader_t__iterator begin, SWIGTYPE_p_std__vectorTaffymetrix_calvin_io__DataSetHeader_t__iterator end) {
    affx_fusionJNI.DataGroupHeader_GetDataSetIterators(swigCPtr, SWIGTYPE_p_std__vectorTaffymetrix_calvin_io__DataSetHeader_t__iterator.getCPtr(begin), SWIGTYPE_p_std__vectorTaffymetrix_calvin_io__DataSetHeader_t__iterator.getCPtr(end));
  }

  public void SetDataSetPos(long pos) {
    affx_fusionJNI.DataGroupHeader_SetDataSetPos(swigCPtr, pos);
  }

  public long GetDataSetPos() {
    return affx_fusionJNI.DataGroupHeader_GetDataSetPos(swigCPtr);
  }

  public void SetNextCubePos(long pos) {
    affx_fusionJNI.DataGroupHeader_SetNextCubePos(swigCPtr, pos);
  }

  public long GetNextCubePos() {
    return affx_fusionJNI.DataGroupHeader_GetNextCubePos(swigCPtr);
  }

  public DataSetHeader FindDataSetHeader(SWIGTYPE_p_std__wstring dataSetName) {
    long cPtr = affx_fusionJNI.DataGroupHeader_FindDataSetHeader(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(dataSetName));
    return (cPtr == 0) ? null : new DataSetHeader(cPtr, false);
  }

}
