/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DataGroup {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_DataGroup(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DataGroup(String filename, DataGroupHeader dch, SWIGTYPE_p_void handle) {
    this(affx_fusionJNI.new_DataGroup(filename, DataGroupHeader.getCPtr(dch), SWIGTYPE_p_void.getCPtr(handle)), true);
  }

  public DataGroupHeader Header() {
    return new DataGroupHeader(affx_fusionJNI.DataGroup_Header(swigCPtr), false);
  }

  public DataSet DataSet(long dataSetIdx) {
    long cPtr = affx_fusionJNI.DataGroup_DataSet__SWIG_0(swigCPtr, dataSetIdx);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet DataSet(SWIGTYPE_p_std__wstring dataSetName) {
    long cPtr = affx_fusionJNI.DataGroup_DataSet__SWIG_1(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(dataSetName));
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

}
