/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DttArrayFileReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DttArrayFileReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DttArrayFileReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_DttArrayFileReader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DttArrayFileReader() {
    this(affx_fusionJNI.new_DttArrayFileReader(), true);
  }

  public String GetFileName() {
    return affx_fusionJNI.DttArrayFileReader_GetFileName(swigCPtr);
  }

  public void SetFileName(String file) {
    affx_fusionJNI.DttArrayFileReader_SetFileName(swigCPtr, file);
  }

  public boolean Read(DttArrayData arrayData) {
    return affx_fusionJNI.DttArrayFileReader_Read(swigCPtr, DttArrayData.getCPtr(arrayData));
  }

  public boolean Exists() {
    return affx_fusionJNI.DttArrayFileReader_Exists(swigCPtr);
  }

}
