/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DttArrayData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DttArrayData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DttArrayData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_DttArrayData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DttArrayData() {
    this(affx_fusionJNI.new_DttArrayData(), true);
  }

  public String GetArrayType() {
    return affx_fusionJNI.DttArrayData_GetArrayType(swigCPtr);
  }

  public void SetArrayType(String aType) {
    affx_fusionJNI.DttArrayData_SetArrayType(swigCPtr, aType);
  }

  public String GetExperimentName() {
    return affx_fusionJNI.DttArrayData_GetExperimentName(swigCPtr);
  }

  public void SetExperimentName(String name) {
    affx_fusionJNI.DttArrayData_SetExperimentName(swigCPtr, name);
  }

  public SWIGTYPE_p_std__listTaffymetrix_dttarray___AttributeNameValueType_t Attributes() {
    return new SWIGTYPE_p_std__listTaffymetrix_dttarray___AttributeNameValueType_t(affx_fusionJNI.DttArrayData_Attributes(swigCPtr), false);
  }

  public void Clear() {
    affx_fusionJNI.DttArrayData_Clear(swigCPtr);
  }

}
