/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FileUtils {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FileUtils(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileUtils obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FileUtils(swigCPtr);
    }
    swigCPtr = 0;
  }

  public static boolean Exists(String fileName) {
    return affx_fusionJNI.FileUtils_Exists(fileName);
  }

  public static boolean LockFile(String fileName) {
    return affx_fusionJNI.FileUtils_LockFile(fileName);
  }

  public static boolean UnlockFile(String fileName) {
    return affx_fusionJNI.FileUtils_UnlockFile(fileName);
  }

  public static SWIGTYPE_p_std__listTstd__string_t ListFiles(String pathName, String ext) {
    return new SWIGTYPE_p_std__listTstd__string_t(affx_fusionJNI.FileUtils_ListFiles(pathName, ext), true);
  }

  public FileUtils() {
    this(affx_fusionJNI.new_FileUtils(), true);
  }

}
