/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FileHeaderReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FileHeaderReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileHeaderReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FileHeaderReader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public FileHeaderReader(SWIGTYPE_p_std__ifstream fs, FileHeader fh) {
    this(affx_fusionJNI.new_FileHeaderReader(SWIGTYPE_p_std__ifstream.getCPtr(fs), FileHeader.getCPtr(fh)), true);
  }

  public void Read() {
    affx_fusionJNI.FileHeaderReader_Read(swigCPtr);
  }

  public long GetDataGroupCnt() {
    return affx_fusionJNI.FileHeaderReader_GetDataGroupCnt(swigCPtr);
  }

  public long GetFirstDataGroupFilePos() {
    return affx_fusionJNI.FileHeaderReader_GetFirstDataGroupFilePos(swigCPtr);
  }

}
