/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FPoint {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FPoint(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setX(float value) {
    affx_fusionJNI.set_FPoint_x(swigCPtr, value);
  }

  public float getX() {
    return affx_fusionJNI.get_FPoint_x(swigCPtr);
  }

  public void setY(float value) {
    affx_fusionJNI.set_FPoint_y(swigCPtr, value);
  }

  public float getY() {
    return affx_fusionJNI.get_FPoint_y(swigCPtr);
  }

  public boolean FPoint_equals(FPoint lhs) {
    return affx_fusionJNI.FPoint_FPoint_equals(swigCPtr, FPoint.getCPtr(lhs));
  }

  public boolean FPoint_not_equals(FPoint lhs) {
    return affx_fusionJNI.FPoint_FPoint_not_equals(swigCPtr, FPoint.getCPtr(lhs));
  }

  public FPoint() {
    this(affx_fusionJNI.new_FPoint(), true);
  }

}
