/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FusionResequencingResults {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FusionResequencingResults(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FusionResequencingResults obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FusionResequencingResults(swigCPtr);
    }
    swigCPtr = 0;
  }

  public FusionResequencingResults() {
    this(affx_fusionJNI.new_FusionResequencingResults(), true);
  }

  public void Clear() {
    affx_fusionJNI.FusionResequencingResults_Clear(swigCPtr);
  }

  public SWIGTYPE_p_std__vectorTchar_t GetCalledBases() {
    return new SWIGTYPE_p_std__vectorTchar_t(affx_fusionJNI.FusionResequencingResults_GetCalledBases(swigCPtr), false);
  }

  public char GetCalledBase(int index) {
    return affx_fusionJNI.FusionResequencingResults_GetCalledBase(swigCPtr, index);
  }

  public int GetCalledBasesSize() {
    return affx_fusionJNI.FusionResequencingResults_GetCalledBasesSize(swigCPtr);
  }

  public void ResizeCalledBases(int size) {
    affx_fusionJNI.FusionResequencingResults_ResizeCalledBases(swigCPtr, size);
  }

  public void SetCalledBase(int index, char call) {
    affx_fusionJNI.FusionResequencingResults_SetCalledBase(swigCPtr, index, call);
  }

  public void AddCalledBase(char call) {
    affx_fusionJNI.FusionResequencingResults_AddCalledBase(swigCPtr, call);
  }

  public SWIGTYPE_p_std__vectorTfloat_t GetScores() {
    return new SWIGTYPE_p_std__vectorTfloat_t(affx_fusionJNI.FusionResequencingResults_GetScores(swigCPtr), false);
  }

  public float GetScore(int index) {
    return affx_fusionJNI.FusionResequencingResults_GetScore(swigCPtr, index);
  }

  public int GetScoresSize() {
    return affx_fusionJNI.FusionResequencingResults_GetScoresSize(swigCPtr);
  }

  public void ResizeScores(int size) {
    affx_fusionJNI.FusionResequencingResults_ResizeScores(swigCPtr, size);
  }

  public void SetScore(int index, float score) {
    affx_fusionJNI.FusionResequencingResults_SetScore(swigCPtr, index, score);
  }

  public void AddScore(float score) {
    affx_fusionJNI.FusionResequencingResults_AddScore(swigCPtr, score);
  }

  public SWIGTYPE_p_std__vectorTaffymetrix_fusion_io__FusionForceCallType_t GetForceCalls() {
    return new SWIGTYPE_p_std__vectorTaffymetrix_fusion_io__FusionForceCallType_t(affx_fusionJNI.FusionResequencingResults_GetForceCalls(swigCPtr), false);
  }

  public FusionForceCallType GetForceCall(int index) {
    return new FusionForceCallType(affx_fusionJNI.FusionResequencingResults_GetForceCall(swigCPtr, index), true);
  }

  public int GetForceCallsSize() {
    return affx_fusionJNI.FusionResequencingResults_GetForceCallsSize(swigCPtr);
  }

  public void ResizeForceCalls(int size) {
    affx_fusionJNI.FusionResequencingResults_ResizeForceCalls(swigCPtr, size);
  }

  public void SetForceCall(int index, FusionForceCallType call) {
    affx_fusionJNI.FusionResequencingResults_SetForceCall(swigCPtr, index, FusionForceCallType.getCPtr(call));
  }

  public void AddForceCall(FusionForceCallType call) {
    affx_fusionJNI.FusionResequencingResults_AddForceCall(swigCPtr, FusionForceCallType.getCPtr(call));
  }

  public SWIGTYPE_p_std__vectorTaffymetrix_fusion_io__FusionBaseCallType_t GetOrigCalls() {
    return new SWIGTYPE_p_std__vectorTaffymetrix_fusion_io__FusionBaseCallType_t(affx_fusionJNI.FusionResequencingResults_GetOrigCalls(swigCPtr), false);
  }

  public FusionBaseCallType GetOrigCall(int index) {
    return new FusionBaseCallType(affx_fusionJNI.FusionResequencingResults_GetOrigCall(swigCPtr, index), true);
  }

  public int GetOrigCallsSize() {
    return affx_fusionJNI.FusionResequencingResults_GetOrigCallsSize(swigCPtr);
  }

  public void ResizeOrigCalls(int size) {
    affx_fusionJNI.FusionResequencingResults_ResizeOrigCalls(swigCPtr, size);
  }

  public void SetOrigCall(int index, FusionBaseCallType call) {
    affx_fusionJNI.FusionResequencingResults_SetOrigCall(swigCPtr, index, FusionBaseCallType.getCPtr(call));
  }

  public void AddOrigCall(FusionBaseCallType call) {
    affx_fusionJNI.FusionResequencingResults_AddOrigCall(swigCPtr, FusionBaseCallType.getCPtr(call));
  }

}
