/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FusionForceCallType {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FusionForceCallType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FusionForceCallType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FusionForceCallType(swigCPtr);
    }
    swigCPtr = 0;
  }

  public FusionForceCallType() {
    this(affx_fusionJNI.new_FusionForceCallType__SWIG_0(), true);
  }

  public FusionForceCallType(int p, char c, short r) {
    this(affx_fusionJNI.new_FusionForceCallType__SWIG_1(p, c, r), true);
  }

  public void Clear() {
    affx_fusionJNI.FusionForceCallType_Clear(swigCPtr);
  }

  public int GetPosition() {
    return affx_fusionJNI.FusionForceCallType_GetPosition(swigCPtr);
  }

  public char GetCall() {
    return affx_fusionJNI.FusionForceCallType_GetCall(swigCPtr);
  }

  public short GetReason() {
    return affx_fusionJNI.FusionForceCallType_GetReason(swigCPtr);
  }

  public void SetPosition(int p) {
    affx_fusionJNI.FusionForceCallType_SetPosition(swigCPtr, p);
  }

  public void SetCall(char p) {
    affx_fusionJNI.FusionForceCallType_SetCall(swigCPtr, p);
  }

  public void SetReason(short p) {
    affx_fusionJNI.FusionForceCallType_SetReason(swigCPtr, p);
  }

}
