/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FusionCDFProbeGroupInformation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FusionCDFProbeGroupInformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FusionCDFProbeGroupInformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FusionCDFProbeGroupInformation(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DirectionType GetDirection() {
    return DirectionType.swigToEnum(affx_fusionJNI.FusionCDFProbeGroupInformation_GetDirection(swigCPtr));
  }

  public int GetNumLists() {
    return affx_fusionJNI.FusionCDFProbeGroupInformation_GetNumLists(swigCPtr);
  }

  public int GetNumCells() {
    return affx_fusionJNI.FusionCDFProbeGroupInformation_GetNumCells(swigCPtr);
  }

  public int GetNumCellsPerList() {
    return affx_fusionJNI.FusionCDFProbeGroupInformation_GetNumCellsPerList(swigCPtr);
  }

  public int GetStart() {
    return affx_fusionJNI.FusionCDFProbeGroupInformation_GetStart(swigCPtr);
  }

  public int GetStop() {
    return affx_fusionJNI.FusionCDFProbeGroupInformation_GetStop(swigCPtr);
  }

  public String GetName() {
    return affx_fusionJNI.FusionCDFProbeGroupInformation_GetName(swigCPtr);
  }

  public void GetCell(int cell_index, FusionCDFProbeInformation info) {
    affx_fusionJNI.FusionCDFProbeGroupInformation_GetCell(swigCPtr, cell_index, FusionCDFProbeInformation.getCPtr(info));
  }

  public FusionCDFProbeGroupInformation() {
    this(affx_fusionJNI.new_FusionCDFProbeGroupInformation(), true);
  }

}
