/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FusionCHPHeader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FusionCHPHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FusionCHPHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FusionCHPHeader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public FusionCHPHeader() {
    this(affx_fusionJNI.new_FusionCHPHeader(), true);
  }

  public int GetCols() {
    return affx_fusionJNI.FusionCHPHeader_GetCols(swigCPtr);
  }

  public int GetRows() {
    return affx_fusionJNI.FusionCHPHeader_GetRows(swigCPtr);
  }

  public int GetNumProbeSets() {
    return affx_fusionJNI.FusionCHPHeader_GetNumProbeSets(swigCPtr);
  }

  public AssayType GetAssayType() {
    return AssayType.swigToEnum(affx_fusionJNI.FusionCHPHeader_GetAssayType(swigCPtr));
  }

  public SWIGTYPE_p_std__wstring GetChipType() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.FusionCHPHeader_GetChipType(swigCPtr), true);
  }

  public SWIGTYPE_p_std__wstring GetAlgName() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.FusionCHPHeader_GetAlgName(swigCPtr), true);
  }

  public SWIGTYPE_p_std__wstring GetAlgVersion() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.FusionCHPHeader_GetAlgVersion(swigCPtr), true);
  }

  public void AlgorithmParameters(SWIGTYPE_p_std__listTaffymetrix_fusion_io__FusionTagValuePairType_t values) {
    affx_fusionJNI.FusionCHPHeader_AlgorithmParameters(swigCPtr, SWIGTYPE_p_std__listTaffymetrix_fusion_io__FusionTagValuePairType_t.getCPtr(values));
  }

  public long AlgorithmParameterCount() {
    return affx_fusionJNI.FusionCHPHeader_AlgorithmParameterCount(swigCPtr);
  }

  public void SummaryParameters(SWIGTYPE_p_std__listTaffymetrix_fusion_io__FusionTagValuePairType_t p) {
    affx_fusionJNI.FusionCHPHeader_SummaryParameters(swigCPtr, SWIGTYPE_p_std__listTaffymetrix_fusion_io__FusionTagValuePairType_t.getCPtr(p));
  }

  public SWIGTYPE_p_std__wstring GetParentCellFile() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.FusionCHPHeader_GetParentCellFile(swigCPtr), true);
  }

  public SWIGTYPE_p_std__wstring GetProgID() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.FusionCHPHeader_GetProgID(swigCPtr), true);
  }

  public SWIGTYPE_p_std__wstring GetAlgorithmParameter(SWIGTYPE_p_wchar_t tag) {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.FusionCHPHeader_GetAlgorithmParameter(swigCPtr, SWIGTYPE_p_wchar_t.getCPtr(tag)), true);
  }

  public SWIGTYPE_p_std__wstring GetSummaryParameter(SWIGTYPE_p_wchar_t tag) {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.FusionCHPHeader_GetSummaryParameter(swigCPtr, SWIGTYPE_p_wchar_t.getCPtr(tag)), true);
  }

  public void GetBackgroundZoneInfo(BackgroundZoneInfo info) {
    affx_fusionJNI.FusionCHPHeader_GetBackgroundZoneInfo(swigCPtr, BackgroundZoneInfo.getCPtr(info));
  }

  public void GetBackgroundZones(SWIGTYPE_p_std__listTaffxchp___BackgroundZoneType_t zones) {
    affx_fusionJNI.FusionCHPHeader_GetBackgroundZones(swigCPtr, SWIGTYPE_p_std__listTaffxchp___BackgroundZoneType_t.getCPtr(zones));
  }

  public void GetBackgroundZone(BackgroundZoneType type, int x, int y) {
    affx_fusionJNI.FusionCHPHeader_GetBackgroundZone(swigCPtr, BackgroundZoneType.getCPtr(type), x, y);
  }

  public int GetMagic() {
    return affx_fusionJNI.FusionCHPHeader_GetMagic(swigCPtr);
  }

  public int GetVersion() {
    return affx_fusionJNI.FusionCHPHeader_GetVersion(swigCPtr);
  }

  public void CheckAdapter() {
    affx_fusionJNI.FusionCHPHeader_CheckAdapter(swigCPtr);
  }

}
