/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FusionCDFData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FusionCDFData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FusionCDFData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FusionCDFData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public FusionCDFData() {
    this(affx_fusionJNI.new_FusionCDFData(), true);
  }

  public void SetFileName(String name) {
    affx_fusionJNI.FusionCDFData_SetFileName(swigCPtr, name);
  }

  public String GetFileName() {
    return affx_fusionJNI.FusionCDFData_GetFileName(swigCPtr);
  }

  public FusionCDFFileHeader GetHeader() {
    return new FusionCDFFileHeader(affx_fusionJNI.FusionCDFData_GetHeader(swigCPtr), false);
  }

  public String GetError() {
    return affx_fusionJNI.FusionCDFData_GetError(swigCPtr);
  }

  public String GetProbeSetName(int index) {
    return affx_fusionJNI.FusionCDFData_GetProbeSetName(swigCPtr, index);
  }

  public String GetChipType() {
    return affx_fusionJNI.FusionCDFData_GetChipType(swigCPtr);
  }

  public boolean Read() {
    return affx_fusionJNI.FusionCDFData_Read(swigCPtr);
  }

  public boolean ReadHeader() {
    return affx_fusionJNI.FusionCDFData_ReadHeader(swigCPtr);
  }

  public boolean Exists() {
    return affx_fusionJNI.FusionCDFData_Exists(swigCPtr);
  }

  public void Close() {
    affx_fusionJNI.FusionCDFData_Close(swigCPtr);
  }

  public static boolean IsXDACompatibleFile(String fileName) {
    return affx_fusionJNI.FusionCDFData_IsXDACompatibleFile(fileName);
  }

  public static boolean IsCalvinCompatibleFile(String fileName) {
    return affx_fusionJNI.FusionCDFData_IsCalvinCompatibleFile(fileName);
  }

  public GeneChipProbeSetType GetProbeSetType(int index) {
    return GeneChipProbeSetType.swigToEnum(affx_fusionJNI.FusionCDFData_GetProbeSetType(swigCPtr, index));
  }

  public void GetProbeSetInformation(int index, FusionCDFProbeSetInformation info) {
    affx_fusionJNI.FusionCDFData_GetProbeSetInformation(swigCPtr, index, FusionCDFProbeSetInformation.getCPtr(info));
  }

  public void GetQCProbeSetInformation(int index, FusionCDFQCProbeSetInformation info) {
    affx_fusionJNI.FusionCDFData_GetQCProbeSetInformation(swigCPtr, index, FusionCDFQCProbeSetInformation.getCPtr(info));
  }

  public void FusionGetQCProbeSetInformation_By_Type(GeneChipQCProbeSetType qcType, FusionCDFQCProbeSetInformation info) {
    affx_fusionJNI.FusionCDFData_FusionGetQCProbeSetInformation_By_Type(swigCPtr, qcType.swigValue(), FusionCDFQCProbeSetInformation.getCPtr(info));
  }

}
