/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FusionGenotypeProbeSetResults extends FusionProbeSetResults {
  private long swigCPtr;

  protected FusionGenotypeProbeSetResults(long cPtr, boolean cMemoryOwn) {
    super(affx_fusionJNI.SWIGFusionGenotypeProbeSetResultsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FusionGenotypeProbeSetResults obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FusionGenotypeProbeSetResults(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void Clear() {
    affx_fusionJNI.FusionGenotypeProbeSetResults_Clear(swigCPtr);
  }

  public short GetAlleleCall() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetAlleleCall(swigCPtr);
  }

  public float GetConfidence() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetConfidence(swigCPtr);
  }

  public float GetRAS1() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetRAS1(swigCPtr);
  }

  public float GetRAS2() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetRAS2(swigCPtr);
  }

  public float GetPValueAA() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetPValueAA(swigCPtr);
  }

  public float GetPValueAB() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetPValueAB(swigCPtr);
  }

  public float GetPValueBB() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetPValueBB(swigCPtr);
  }

  public float GetPValueNoCall() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetPValueNoCall(swigCPtr);
  }

  public void SetAlleleCall(short p) {
    affx_fusionJNI.FusionGenotypeProbeSetResults_SetAlleleCall(swigCPtr, p);
  }

  public void SetConfidence(float p) {
    affx_fusionJNI.FusionGenotypeProbeSetResults_SetConfidence(swigCPtr, p);
  }

  public void SetRAS1(float p) {
    affx_fusionJNI.FusionGenotypeProbeSetResults_SetRAS1(swigCPtr, p);
  }

  public void SetRAS2(float p) {
    affx_fusionJNI.FusionGenotypeProbeSetResults_SetRAS2(swigCPtr, p);
  }

  public void SetPValueAA(float p) {
    affx_fusionJNI.FusionGenotypeProbeSetResults_SetPValueAA(swigCPtr, p);
  }

  public void SetPValueAB(float p) {
    affx_fusionJNI.FusionGenotypeProbeSetResults_SetPValueAB(swigCPtr, p);
  }

  public void SetPValueBB(float p) {
    affx_fusionJNI.FusionGenotypeProbeSetResults_SetPValueBB(swigCPtr, p);
  }

  public void SetPValueNoCall(float p) {
    affx_fusionJNI.FusionGenotypeProbeSetResults_SetPValueNoCall(swigCPtr, p);
  }

  public String GetAlleleCallString() {
    return affx_fusionJNI.FusionGenotypeProbeSetResults_GetAlleleCallString(swigCPtr);
  }

  public FusionGenotypeProbeSetResults FusionGenotypeProbeSetResults_assign(FusionGenotypeProbeSetResults src) {
    return new FusionGenotypeProbeSetResults(affx_fusionJNI.FusionGenotypeProbeSetResults_FusionGenotypeProbeSetResults_assign(swigCPtr, FusionGenotypeProbeSetResults.getCPtr(src)), true);
  }

  public FusionGenotypeProbeSetResults() {
    this(affx_fusionJNI.new_FusionGenotypeProbeSetResults(), true);
  }

}
