/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FusionCDFProbeSetInformation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FusionCDFProbeSetInformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FusionCDFProbeSetInformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_FusionCDFProbeSetInformation(swigCPtr);
    }
    swigCPtr = 0;
  }

  public GeneChipProbeSetType GetProbeSetType() {
    return GeneChipProbeSetType.swigToEnum(affx_fusionJNI.FusionCDFProbeSetInformation_GetProbeSetType(swigCPtr));
  }

  public DirectionType GetDirection() {
    return DirectionType.swigToEnum(affx_fusionJNI.FusionCDFProbeSetInformation_GetDirection(swigCPtr));
  }

  public int GetNumLists() {
    return affx_fusionJNI.FusionCDFProbeSetInformation_GetNumLists(swigCPtr);
  }

  public int GetNumGroups() {
    return affx_fusionJNI.FusionCDFProbeSetInformation_GetNumGroups(swigCPtr);
  }

  public int GetNumCells() {
    return affx_fusionJNI.FusionCDFProbeSetInformation_GetNumCells(swigCPtr);
  }

  public int GetNumCellsPerList() {
    return affx_fusionJNI.FusionCDFProbeSetInformation_GetNumCellsPerList(swigCPtr);
  }

  public int GetProbeSetNumber() {
    return affx_fusionJNI.FusionCDFProbeSetInformation_GetProbeSetNumber(swigCPtr);
  }

  public void GetGroupInformation(int index, FusionCDFProbeGroupInformation info) {
    affx_fusionJNI.FusionCDFProbeSetInformation_GetGroupInformation(swigCPtr, index, FusionCDFProbeGroupInformation.getCPtr(info));
  }

  public FusionCDFProbeSetInformation() {
    this(affx_fusionJNI.new_FusionCDFProbeSetInformation(), true);
  }

}
