/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class GDACFILES_BAR_DATA_TYPE {
  public final static GDACFILES_BAR_DATA_TYPE BAR_DATA_DOUBLE = new GDACFILES_BAR_DATA_TYPE("BAR_DATA_DOUBLE");
  public final static GDACFILES_BAR_DATA_TYPE BAR_DATA_FLOAT = new GDACFILES_BAR_DATA_TYPE("BAR_DATA_FLOAT");
  public final static GDACFILES_BAR_DATA_TYPE BAR_DATA_INTEGER = new GDACFILES_BAR_DATA_TYPE("BAR_DATA_INTEGER");
  public final static GDACFILES_BAR_DATA_TYPE BAR_DATA_SHORT = new GDACFILES_BAR_DATA_TYPE("BAR_DATA_SHORT");
  public final static GDACFILES_BAR_DATA_TYPE BAR_DATA_CHAR = new GDACFILES_BAR_DATA_TYPE("BAR_DATA_CHAR");
  public final static GDACFILES_BAR_DATA_TYPE BAR_DATA_UINTEGER = new GDACFILES_BAR_DATA_TYPE("BAR_DATA_UINTEGER");
  public final static GDACFILES_BAR_DATA_TYPE BAR_DATA_USHORT = new GDACFILES_BAR_DATA_TYPE("BAR_DATA_USHORT");
  public final static GDACFILES_BAR_DATA_TYPE BAR_DATA_UCHAR = new GDACFILES_BAR_DATA_TYPE("BAR_DATA_UCHAR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GDACFILES_BAR_DATA_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GDACFILES_BAR_DATA_TYPE.class + " with value " + swigValue);
  }

  private GDACFILES_BAR_DATA_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GDACFILES_BAR_DATA_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private static GDACFILES_BAR_DATA_TYPE[] swigValues = { BAR_DATA_DOUBLE, BAR_DATA_FLOAT, BAR_DATA_INTEGER, BAR_DATA_SHORT, BAR_DATA_CHAR, BAR_DATA_UINTEGER, BAR_DATA_USHORT, BAR_DATA_UCHAR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

