/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class GDACSequenceHitItemType {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GDACSequenceHitItemType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GDACSequenceHitItemType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_GDACSequenceHitItemType(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setPMX(long value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_PMX(swigCPtr, value);
  }

  public long getPMX() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_PMX(swigCPtr);
  }

  public void setPMY(long value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_PMY(swigCPtr, value);
  }

  public long getPMY() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_PMY(swigCPtr);
  }

  public void setMMX(long value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_MMX(swigCPtr, value);
  }

  public long getMMX() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_MMX(swigCPtr);
  }

  public void setMMY(long value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_MMY(swigCPtr, value);
  }

  public long getMMY() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_MMY(swigCPtr);
  }

  public void setMatchScore(float value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_MatchScore(swigCPtr, value);
  }

  public float getMatchScore() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_MatchScore(swigCPtr);
  }

  public void setPosition(long value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_Position(swigCPtr, value);
  }

  public long getPosition() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_Position(swigCPtr);
  }

  public void setPMProbe(SWIGTYPE_p_std__string value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_PMProbe(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getPMProbe() {
    long cPtr = affx_fusionJNI.get_GDACSequenceHitItemType_PMProbe(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void setProbeLength(short value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_ProbeLength(swigCPtr, value);
  }

  public short getProbeLength() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_ProbeLength(swigCPtr);
  }

  public void setTopStrand(short value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_TopStrand(swigCPtr, value);
  }

  public short getTopStrand() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_TopStrand(swigCPtr);
  }

  public boolean _GDACSequenceHitItemType_less_than(GDACSequenceHitItemType rhs) {
    return affx_fusionJNI.GDACSequenceHitItemType__GDACSequenceHitItemType_less_than(swigCPtr, GDACSequenceHitItemType.getCPtr(rhs));
  }

  public void setPackedPMProbe(String value) {
    affx_fusionJNI.set_GDACSequenceHitItemType_PackedPMProbe(swigCPtr, value);
  }

  public String getPackedPMProbe() {
    return affx_fusionJNI.get_GDACSequenceHitItemType_PackedPMProbe(swigCPtr);
  }

  public GDACSequenceHitItemType() {
    this(affx_fusionJNI.new_GDACSequenceHitItemType(), true);
  }

}
