/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class GenericDataHeaderReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GenericDataHeaderReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GenericDataHeaderReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_GenericDataHeaderReader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public GenericDataHeaderReader(SWIGTYPE_p_std__ifstream fs) {
    this(affx_fusionJNI.new_GenericDataHeaderReader(SWIGTYPE_p_std__ifstream.getCPtr(fs)), true);
  }

  public void Read(GenericDataHeader gdh) {
    affx_fusionJNI.GenericDataHeaderReader_Read(swigCPtr, GenericDataHeader.getCPtr(gdh));
  }

}
