/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class GenericData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GenericData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GenericData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_GenericData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public GenericData() {
    this(affx_fusionJNI.new_GenericData(), true);
  }

  public String FileIdentifier() {
    return affx_fusionJNI.GenericData_FileIdentifier(swigCPtr);
  }

  public String ArrayFileIdentifier() {
    return affx_fusionJNI.GenericData_ArrayFileIdentifier(swigCPtr);
  }

  public FileHeader Header() {
    return new FileHeader(affx_fusionJNI.GenericData_Header(swigCPtr), false);
  }

  public long DataGroupCnt() {
    return affx_fusionJNI.GenericData_DataGroupCnt(swigCPtr);
  }

  public void DataGroupNames(SWIGTYPE_p_std__vectorTstd__wstring_t names) {
    affx_fusionJNI.GenericData_DataGroupNames(swigCPtr, SWIGTYPE_p_std__vectorTstd__wstring_t.getCPtr(names));
  }

  public long DataSetCnt(long dataGroupIdx) {
    return affx_fusionJNI.GenericData_DataSetCnt__SWIG_0(swigCPtr, dataGroupIdx);
  }

  public long DataSetCnt(SWIGTYPE_p_std__wstring dataGroupName) {
    return affx_fusionJNI.GenericData_DataSetCnt__SWIG_1(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(dataGroupName));
  }

  public void DataSetNames(long dataGroupIdx, SWIGTYPE_p_std__vectorTstd__wstring_t names) {
    affx_fusionJNI.GenericData_DataSetNames__SWIG_0(swigCPtr, dataGroupIdx, SWIGTYPE_p_std__vectorTstd__wstring_t.getCPtr(names));
  }

  public void DataSetNames(SWIGTYPE_p_std__wstring dataGroupName, SWIGTYPE_p_std__vectorTstd__wstring_t names) {
    affx_fusionJNI.GenericData_DataSetNames__SWIG_1(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(dataGroupName), SWIGTYPE_p_std__vectorTstd__wstring_t.getCPtr(names));
  }

  public DataSet DataSet(long dataGroupIdx, long dataSetIdx) {
    long cPtr = affx_fusionJNI.GenericData_DataSet__SWIG_0(swigCPtr, dataGroupIdx, dataSetIdx);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet DataSet(SWIGTYPE_p_std__wstring dataGroupName, SWIGTYPE_p_std__wstring dataSetName) {
    long cPtr = affx_fusionJNI.GenericData_DataSet__SWIG_1(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(dataGroupName), SWIGTYPE_p_std__wstring.getCPtr(dataSetName));
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataGroup DataGroup(long dataGroupFilePos) {
    return new DataGroup(affx_fusionJNI.GenericData_DataGroup(swigCPtr, dataGroupFilePos), true);
  }

  public void Clear() {
    affx_fusionJNI.GenericData_Clear(swigCPtr);
  }

  public void ReadFullDataSetHeader(DataSetHeader dph) {
    affx_fusionJNI.GenericData_ReadFullDataSetHeader(swigCPtr, DataSetHeader.getCPtr(dph));
  }

  public boolean IsDPHPartiallyRead(DataSetHeader dph) {
    return affx_fusionJNI.GenericData_IsDPHPartiallyRead(swigCPtr, DataSetHeader.getCPtr(dph));
  }

  public void OpenFStream(SWIGTYPE_p_std__ifstream fileStream) {
    affx_fusionJNI.GenericData_OpenFStream(swigCPtr, SWIGTYPE_p_std__ifstream.getCPtr(fileStream));
  }

  public DataGroupHeader FindDataGroupHeader(SWIGTYPE_p_std__wstring name) {
    long cPtr = affx_fusionJNI.GenericData_FindDataGroupHeader__SWIG_0(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(name));
    return (cPtr == 0) ? null : new DataGroupHeader(cPtr, false);
  }

  public DataGroupHeader FindDataGroupHeader(int index) {
    long cPtr = affx_fusionJNI.GenericData_FindDataGroupHeader__SWIG_1(swigCPtr, index);
    return (cPtr == 0) ? null : new DataGroupHeader(cPtr, false);
  }

  public static DataSetHeader FindDataSetHeader(DataGroupHeader dch, long dataSetIdx) {
    long cPtr = affx_fusionJNI.GenericData_FindDataSetHeader__SWIG_0(DataGroupHeader.getCPtr(dch), dataSetIdx);
    return (cPtr == 0) ? null : new DataSetHeader(cPtr, false);
  }

  public static DataSetHeader FindDataSetHeader(DataGroupHeader dch, SWIGTYPE_p_std__wstring dataSetName) {
    long cPtr = affx_fusionJNI.GenericData_FindDataSetHeader__SWIG_1(DataGroupHeader.getCPtr(dch), SWIGTYPE_p_std__wstring.getCPtr(dataSetName));
    return (cPtr == 0) ? null : new DataSetHeader(cPtr, false);
  }

  public boolean MapFile() {
    return affx_fusionJNI.GenericData_MapFile(swigCPtr);
  }

  public void UnmapFile() {
    affx_fusionJNI.GenericData_UnmapFile(swigCPtr);
  }

}
