/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ParameterNameValuePair {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ParameterNameValuePair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterNameValuePair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_ParameterNameValuePair(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setName(SWIGTYPE_p_std__wstring value) {
    affx_fusionJNI.set_ParameterNameValuePair_Name(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getName() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.get_ParameterNameValuePair_Name(swigCPtr), true);
  }

  public void setValue(SWIGTYPE_p_std__wstring value) {
    affx_fusionJNI.set_ParameterNameValuePair_Value(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getValue() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.get_ParameterNameValuePair_Value(swigCPtr), true);
  }

  public ParameterNameValuePair ParameterNameValuePair_copy(ParameterNameValuePair param) {
    return new ParameterNameValuePair(affx_fusionJNI.ParameterNameValuePair_ParameterNameValuePair_copy(swigCPtr, ParameterNameValuePair.getCPtr(param)), true);
  }

  public boolean ParameterNameValuePair_equals_obj(ParameterNameValuePair param) {
    return affx_fusionJNI.ParameterNameValuePair_ParameterNameValuePair_equals_obj(swigCPtr, ParameterNameValuePair.getCPtr(param));
  }

  public boolean ParameterNameValueControlVocabulary_equals_name(SWIGTYPE_p_std__wstring name) {
    return affx_fusionJNI.ParameterNameValuePair_ParameterNameValueControlVocabulary_equals_name(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(name));
  }

  public ParameterNameValuePair() {
    this(affx_fusionJNI.new_ParameterNameValuePair(), true);
  }

}
