/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ParameterNameValueControlVocabulary {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ParameterNameValueControlVocabulary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterNameValueControlVocabulary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_ParameterNameValueControlVocabulary(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setName(SWIGTYPE_p_std__wstring value) {
    affx_fusionJNI.set_ParameterNameValueControlVocabulary_Name(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getName() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.get_ParameterNameValueControlVocabulary_Name(swigCPtr), true);
  }

  public void setValue(SWIGTYPE_p_std__wstring value) {
    affx_fusionJNI.set_ParameterNameValueControlVocabulary_Value(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getValue() {
    return new SWIGTYPE_p_std__wstring(affx_fusionJNI.get_ParameterNameValueControlVocabulary_Value(swigCPtr), true);
  }

  public void setControlledVocabulary(SWIGTYPE_p_std__vectorTstd__wstring_t value) {
    affx_fusionJNI.set_ParameterNameValueControlVocabulary_ControlledVocabulary(swigCPtr, SWIGTYPE_p_std__vectorTstd__wstring_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorTstd__wstring_t getControlledVocabulary() {
    long cPtr = affx_fusionJNI.get_ParameterNameValueControlVocabulary_ControlledVocabulary(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorTstd__wstring_t(cPtr, false);
  }

  public ParameterNameValueControlVocabulary ParameterNameValueControlVocabulary_copy(ParameterNameValueControlVocabulary param) {
    return new ParameterNameValueControlVocabulary(affx_fusionJNI.ParameterNameValueControlVocabulary_ParameterNameValueControlVocabulary_copy(swigCPtr, ParameterNameValueControlVocabulary.getCPtr(param)), true);
  }

  public boolean ParameterNameValueControlVocabulary_equals_obj(ParameterNameValueControlVocabulary param) {
    return affx_fusionJNI.ParameterNameValueControlVocabulary_ParameterNameValueControlVocabulary_equals_obj(swigCPtr, ParameterNameValueControlVocabulary.getCPtr(param));
  }

  public boolean ParameterNameValueControlVocabulary_equals_name(SWIGTYPE_p_std__wstring name) {
    return affx_fusionJNI.ParameterNameValueControlVocabulary_ParameterNameValueControlVocabulary_equals_name(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(name));
  }

  public ParameterNameValueControlVocabulary() {
    this(affx_fusionJNI.new_ParameterNameValueControlVocabulary(), true);
  }

}
