/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Rect {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Rect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Rect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_Rect(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Rect() {
    this(affx_fusionJNI.new_Rect__SWIG_0(), true);
  }

  public Rect(Region r) {
    this(affx_fusionJNI.new_Rect__SWIG_1(Region.getCPtr(r)), true);
  }

  public Region op_Region() {
    return new Region(affx_fusionJNI.Rect_op_Region(swigCPtr), true);
  }

  public boolean IsEmpty() {
    return affx_fusionJNI.Rect_IsEmpty(swigCPtr);
  }

  public void setUpperleft(Point value) {
    affx_fusionJNI.set_Rect_upperleft(swigCPtr, Point.getCPtr(value));
  }

  public Point getUpperleft() {
    long cPtr = affx_fusionJNI.get_Rect_upperleft(swigCPtr);
    return (cPtr == 0) ? null : new Point(cPtr, false);
  }

  public void setUpperright(Point value) {
    affx_fusionJNI.set_Rect_upperright(swigCPtr, Point.getCPtr(value));
  }

  public Point getUpperright() {
    long cPtr = affx_fusionJNI.get_Rect_upperright(swigCPtr);
    return (cPtr == 0) ? null : new Point(cPtr, false);
  }

  public void setLowerright(Point value) {
    affx_fusionJNI.set_Rect_lowerright(swigCPtr, Point.getCPtr(value));
  }

  public Point getLowerright() {
    long cPtr = affx_fusionJNI.get_Rect_lowerright(swigCPtr);
    return (cPtr == 0) ? null : new Point(cPtr, false);
  }

  public void setLowerleft(Point value) {
    affx_fusionJNI.set_Rect_lowerleft(swigCPtr, Point.getCPtr(value));
  }

  public Point getLowerleft() {
    long cPtr = affx_fusionJNI.get_Rect_lowerleft(swigCPtr);
    return (cPtr == 0) ? null : new Point(cPtr, false);
  }

}
