/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class RectanglePositions {
  public final static RectanglePositions UpperLeft = new RectanglePositions("UpperLeft", affx_fusionJNI.get_UpperLeft());
  public final static RectanglePositions UpperRight = new RectanglePositions("UpperRight");
  public final static RectanglePositions LowerRight = new RectanglePositions("LowerRight");
  public final static RectanglePositions LowerLeft = new RectanglePositions("LowerLeft");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static RectanglePositions swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + RectanglePositions.class + " with value " + swigValue);
  }

  private RectanglePositions(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private RectanglePositions(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private static RectanglePositions[] swigValues = { UpperLeft, UpperRight, LowerRight, LowerLeft };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

