/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Subgrid {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Subgrid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Subgrid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionJNI.delete_Subgrid(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setRow(int value) {
    affx_fusionJNI.set_Subgrid_row(swigCPtr, value);
  }

  public int getRow() {
    return affx_fusionJNI.get_Subgrid_row(swigCPtr);
  }

  public void setCol(int value) {
    affx_fusionJNI.set_Subgrid_col(swigCPtr, value);
  }

  public int getCol() {
    return affx_fusionJNI.get_Subgrid_col(swigCPtr);
  }

  public void setPixelgrid(FRect value) {
    affx_fusionJNI.set_Subgrid_pixelgrid(swigCPtr, FRect.getCPtr(value));
  }

  public FRect getPixelgrid() {
    long cPtr = affx_fusionJNI.get_Subgrid_pixelgrid(swigCPtr);
    return (cPtr == 0) ? null : new FRect(cPtr, false);
  }

  public void setCellgrid(Rect value) {
    affx_fusionJNI.set_Subgrid_cellgrid(swigCPtr, Rect.getCPtr(value));
  }

  public Rect getCellgrid() {
    long cPtr = affx_fusionJNI.get_Subgrid_cellgrid(swigCPtr);
    return (cPtr == 0) ? null : new Rect(cPtr, false);
  }

  public Subgrid() {
    this(affx_fusionJNI.new_Subgrid(), true);
  }

}
