/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_affymetrix_grid_control__GridControlData {
  private long swigCPtr;

  protected SWIGTYPE_p_affymetrix_grid_control__GridControlData(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_affymetrix_grid_control__GridControlData() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_affymetrix_grid_control__GridControlData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

