/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class AffymetrixGuid : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AffymetrixGuid(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(AffymetrixGuid obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~AffymetrixGuid() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_AffymetrixGuid(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public AffymetrixGuid() : this(affx_fusionPINVOKE.new_AffymetrixGuid(), true) {
  }

  public static string GenerateNewGuid() {
    string ret = affx_fusionPINVOKE.AffymetrixGuid_GenerateNewGuid();
    return ret;
  }

}
