/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ArrayAttributes : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ArrayAttributes(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ArrayAttributes obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArrayAttributes() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_ArrayAttributes(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public ArrayAttributes() : this(affx_fusionPINVOKE.new_ArrayAttributes(), true) {
  }

  public SWIGTYPE_p_std__string Identifier() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(affx_fusionPINVOKE.ArrayAttributes_Identifier(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorTaffymetrix_calvin_parameter___tagParameterNameValuePair_t Attributes() {
    SWIGTYPE_p_std__vectorTaffymetrix_calvin_parameter___tagParameterNameValuePair_t ret = new SWIGTYPE_p_std__vectorTaffymetrix_calvin_parameter___tagParameterNameValuePair_t(affx_fusionPINVOKE.ArrayAttributes_Attributes(swigCPtr), false);
    return ret;
  }

  public void Clear() {
    affx_fusionPINVOKE.ArrayAttributes_Clear(swigCPtr);
  }

}
