/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class AttributeNameValueType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AttributeNameValueType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(AttributeNameValueType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~AttributeNameValueType() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_AttributeNameValueType(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public SWIGTYPE_p_std__string name {
    set {
      affx_fusionPINVOKE.set_AttributeNameValueType_name(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_AttributeNameValueType_name(swigCPtr);
      SWIGTYPE_p_std__string ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_std__string(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__string value {
    set {
      affx_fusionPINVOKE.set_AttributeNameValueType_value(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_AttributeNameValueType_value(swigCPtr);
      SWIGTYPE_p_std__string ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_std__string(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__string type {
    set {
      affx_fusionPINVOKE.set_AttributeNameValueType_type(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_AttributeNameValueType_type(swigCPtr);
      SWIGTYPE_p_std__string ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_std__string(cPtr, false);
      return ret;
    } 
  }

  public AttributeNameValueType() : this(affx_fusionPINVOKE.new_AttributeNameValueType(), true) {
  }

}
