/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class BackgroundZoneInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BackgroundZoneInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BackgroundZoneInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BackgroundZoneInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_BackgroundZoneInfo(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public int number_zones {
    set {
      affx_fusionPINVOKE.set_BackgroundZoneInfo_number_zones(swigCPtr, value);
    } 
    get {
      int ret = affx_fusionPINVOKE.get_BackgroundZoneInfo_number_zones(swigCPtr);
      return ret;
    } 
  }

  public float smooth_factor {
    set {
      affx_fusionPINVOKE.set_BackgroundZoneInfo_smooth_factor(swigCPtr, value);
    } 
    get {
      float ret = affx_fusionPINVOKE.get_BackgroundZoneInfo_smooth_factor(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__listTaffxchp___BackgroundZoneType_t zones {
    set {
      affx_fusionPINVOKE.set_BackgroundZoneInfo_zones(swigCPtr, SWIGTYPE_p_std__listTaffxchp___BackgroundZoneType_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_BackgroundZoneInfo_zones(swigCPtr);
      SWIGTYPE_p_std__listTaffxchp___BackgroundZoneType_t ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_std__listTaffxchp___BackgroundZoneType_t(cPtr, false);
      return ret;
    } 
  }

  public BackgroundZoneInfo() : this(affx_fusionPINVOKE.new_BackgroundZoneInfo(), true) {
  }

}
