/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class BackgroundZoneType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BackgroundZoneType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BackgroundZoneType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BackgroundZoneType() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_BackgroundZoneType(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public float centerx {
    set {
      affx_fusionPINVOKE.set_BackgroundZoneType_centerx(swigCPtr, value);
    } 
    get {
      float ret = affx_fusionPINVOKE.get_BackgroundZoneType_centerx(swigCPtr);
      return ret;
    } 
  }

  public float centery {
    set {
      affx_fusionPINVOKE.set_BackgroundZoneType_centery(swigCPtr, value);
    } 
    get {
      float ret = affx_fusionPINVOKE.get_BackgroundZoneType_centery(swigCPtr);
      return ret;
    } 
  }

  public float background {
    set {
      affx_fusionPINVOKE.set_BackgroundZoneType_background(swigCPtr, value);
    } 
    get {
      float ret = affx_fusionPINVOKE.get_BackgroundZoneType_background(swigCPtr);
      return ret;
    } 
  }

  public BackgroundZoneType _BackgroundZoneType_assign(BackgroundZoneType zn) {
    BackgroundZoneType ret = new BackgroundZoneType(affx_fusionPINVOKE.BackgroundZoneType__BackgroundZoneType_assign(swigCPtr, BackgroundZoneType.getCPtr(zn)), true);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public BackgroundZoneType() : this(affx_fusionPINVOKE.new_BackgroundZoneType(), true) {
  }

}
