/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class BarSequenceResultData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BarSequenceResultData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BarSequenceResultData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BarSequenceResultData() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_BarSequenceResultData(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public double dValue {
    set {
      affx_fusionPINVOKE.set_BarSequenceResultData_dValue(swigCPtr, value);
    } 
    get {
      double ret = affx_fusionPINVOKE.get_BarSequenceResultData_dValue(swigCPtr);
      return ret;
    } 
  }

  public float fValue {
    set {
      affx_fusionPINVOKE.set_BarSequenceResultData_fValue(swigCPtr, value);
    } 
    get {
      float ret = affx_fusionPINVOKE.get_BarSequenceResultData_fValue(swigCPtr);
      return ret;
    } 
  }

  public int iValue {
    set {
      affx_fusionPINVOKE.set_BarSequenceResultData_iValue(swigCPtr, value);
    } 
    get {
      int ret = affx_fusionPINVOKE.get_BarSequenceResultData_iValue(swigCPtr);
      return ret;
    } 
  }

  public short sValue {
    set {
      affx_fusionPINVOKE.set_BarSequenceResultData_sValue(swigCPtr, value);
    } 
    get {
      short ret = affx_fusionPINVOKE.get_BarSequenceResultData_sValue(swigCPtr);
      return ret;
    } 
  }

  public char cValue {
    set {
      affx_fusionPINVOKE.set_BarSequenceResultData_cValue(swigCPtr, value);
    } 
    get {
      char ret = affx_fusionPINVOKE.get_BarSequenceResultData_cValue(swigCPtr);
      return ret;
    } 
  }

  public uint uiValue {
    set {
      affx_fusionPINVOKE.set_BarSequenceResultData_uiValue(swigCPtr, value);
    } 
    get {
      uint ret = affx_fusionPINVOKE.get_BarSequenceResultData_uiValue(swigCPtr);
      return ret;
    } 
  }

  public ushort usValue {
    set {
      affx_fusionPINVOKE.set_BarSequenceResultData_usValue(swigCPtr, value);
    } 
    get {
      ushort ret = affx_fusionPINVOKE.get_BarSequenceResultData_usValue(swigCPtr);
      return ret;
    } 
  }

  public byte ucValue {
    set {
      affx_fusionPINVOKE.set_BarSequenceResultData_ucValue(swigCPtr, value);
    } 
    get {
      byte ret = affx_fusionPINVOKE.get_BarSequenceResultData_ucValue(swigCPtr);
      return ret;
    } 
  }

  public BarSequenceResultData() : this(affx_fusionPINVOKE.new_BarSequenceResultData(), true) {
  }

}
