/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CBPMAPFileData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CBPMAPFileData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CBPMAPFileData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CBPMAPFileData() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CBPMAPFileData(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CBPMAPFileData() : this(affx_fusionPINVOKE.new_CBPMAPFileData(), true) {
  }

  public void SetFileName(string name) {
    affx_fusionPINVOKE.CBPMAPFileData_SetFileName(swigCPtr, name);
  }

  public string GetFileName() {
    string ret = affx_fusionPINVOKE.CBPMAPFileData_GetFileName(swigCPtr);
    return ret;
  }

  public bool Read() {
    bool ret = affx_fusionPINVOKE.CBPMAPFileData_Read(swigCPtr);
    return ret;
  }

  public bool ReadHeader() {
    bool ret = affx_fusionPINVOKE.CBPMAPFileData_ReadHeader(swigCPtr);
    return ret;
  }

  public bool Exists() {
    bool ret = affx_fusionPINVOKE.CBPMAPFileData_Exists(swigCPtr);
    return ret;
  }

  public void Close() {
    affx_fusionPINVOKE.CBPMAPFileData_Close(swigCPtr);
  }

  public string GetError() {
    string ret = affx_fusionPINVOKE.CBPMAPFileData_GetError(swigCPtr);
    return ret;
  }

  public int GetNumberSequences() {
    int ret = affx_fusionPINVOKE.CBPMAPFileData_GetNumberSequences(swigCPtr);
    return ret;
  }

  public float GetVersion() {
    float ret = affx_fusionPINVOKE.CBPMAPFileData_GetVersion(swigCPtr);
    return ret;
  }

  public void GetSequenceItem(int index, CGDACSequenceItem seq) {
    affx_fusionPINVOKE.CBPMAPFileData_GetSequenceItem(swigCPtr, index, CGDACSequenceItem.getCPtr(seq));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

}
