/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CCDFProbeInformation : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CCDFProbeInformation(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CCDFProbeInformation obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CCDFProbeInformation() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CCDFProbeInformation(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public int GetListIndex() {
    int ret = affx_fusionPINVOKE.CCDFProbeInformation_GetListIndex(swigCPtr);
    return ret;
  }

  public int GetExpos() {
    int ret = affx_fusionPINVOKE.CCDFProbeInformation_GetExpos(swigCPtr);
    return ret;
  }

  public int GetX() {
    int ret = affx_fusionPINVOKE.CCDFProbeInformation_GetX(swigCPtr);
    return ret;
  }

  public int GetY() {
    int ret = affx_fusionPINVOKE.CCDFProbeInformation_GetY(swigCPtr);
    return ret;
  }

  public char GetPBase() {
    char ret = affx_fusionPINVOKE.CCDFProbeInformation_GetPBase(swigCPtr);
    return ret;
  }

  public char GetTBase() {
    char ret = affx_fusionPINVOKE.CCDFProbeInformation_GetTBase(swigCPtr);
    return ret;
  }

  public CCDFProbeInformation() : this(affx_fusionPINVOKE.new_CCDFProbeInformation(), true) {
  }

}
