/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CCDFProbeSetInformation : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CCDFProbeSetInformation(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CCDFProbeSetInformation obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CCDFProbeSetInformation() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CCDFProbeSetInformation(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public GeneChipProbeSetType GetProbeSetType() {
    GeneChipProbeSetType ret = (GeneChipProbeSetType)affx_fusionPINVOKE.CCDFProbeSetInformation_GetProbeSetType(swigCPtr);
    return ret;
  }

  public DirectionType GetDirection() {
    DirectionType ret = (DirectionType)affx_fusionPINVOKE.CCDFProbeSetInformation_GetDirection(swigCPtr);
    return ret;
  }

  public int GetNumLists() {
    int ret = affx_fusionPINVOKE.CCDFProbeSetInformation_GetNumLists(swigCPtr);
    return ret;
  }

  public int GetNumGroups() {
    int ret = affx_fusionPINVOKE.CCDFProbeSetInformation_GetNumGroups(swigCPtr);
    return ret;
  }

  public int GetNumCells() {
    int ret = affx_fusionPINVOKE.CCDFProbeSetInformation_GetNumCells(swigCPtr);
    return ret;
  }

  public int GetNumCellsPerList() {
    int ret = affx_fusionPINVOKE.CCDFProbeSetInformation_GetNumCellsPerList(swigCPtr);
    return ret;
  }

  public int GetProbeSetNumber() {
    int ret = affx_fusionPINVOKE.CCDFProbeSetInformation_GetProbeSetNumber(swigCPtr);
    return ret;
  }

  public void GetGroupInformation(int index, CCDFProbeGroupInformation info) {
    affx_fusionPINVOKE.CCDFProbeSetInformation_GetGroupInformation(swigCPtr, index, CCDFProbeGroupInformation.getCPtr(info));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public CCDFProbeSetInformation() : this(affx_fusionPINVOKE.new_CCDFProbeSetInformation(), true) {
  }

}
