/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CCELFileData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CCELFileData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CCELFileData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CCELFileData() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CCELFileData(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CCELFileData() : this(affx_fusionPINVOKE.new_CCELFileData(), true) {
  }

  public void SetError(string str) {
    affx_fusionPINVOKE.CCELFileData_SetError(swigCPtr, str);
  }

  public string GetError() {
    string ret = affx_fusionPINVOKE.CCELFileData_GetError(swigCPtr);
    return ret;
  }

  public CCELFileData GetThisPtr() {
    IntPtr cPtr = affx_fusionPINVOKE.CCELFileData_GetThisPtr(swigCPtr);
    CCELFileData ret = (cPtr == IntPtr.Zero) ? null : new CCELFileData(cPtr, false);
    return ret;
  }

  public void SetFileName(string str) {
    affx_fusionPINVOKE.CCELFileData_SetFileName(swigCPtr, str);
  }

  public string GetFileName() {
    string ret = affx_fusionPINVOKE.CCELFileData_GetFileName(swigCPtr);
    return ret;
  }

  public string GetHeaderKey(string key) {
    string ret = affx_fusionPINVOKE.CCELFileData_GetHeaderKey(swigCPtr, key);
    return ret;
  }

  public int GetVersion() {
    int ret = affx_fusionPINVOKE.CCELFileData_GetVersion(swigCPtr);
    return ret;
  }

  public int GetCols() {
    int ret = affx_fusionPINVOKE.CCELFileData_GetCols(swigCPtr);
    return ret;
  }

  public int GetRows() {
    int ret = affx_fusionPINVOKE.CCELFileData_GetRows(swigCPtr);
    return ret;
  }

  public int GetNumCells() {
    int ret = affx_fusionPINVOKE.CCELFileData_GetNumCells(swigCPtr);
    return ret;
  }

  public string GetHeaderString() {
    string ret = affx_fusionPINVOKE.CCELFileData_GetHeaderString(swigCPtr);
    return ret;
  }

  public CCELFileHeaderData GetHeader() {
    CCELFileHeaderData ret = new CCELFileHeaderData(affx_fusionPINVOKE.CCELFileData_GetHeader(swigCPtr), false);
    return ret;
  }

  public string GetAlg() {
    string ret = affx_fusionPINVOKE.CCELFileData_GetAlg(swigCPtr);
    return ret;
  }

  public string GetParams() {
    string ret = affx_fusionPINVOKE.CCELFileData_GetParams(swigCPtr);
    return ret;
  }

  public string GetAlgorithmParameter(string tag) {
    string ret = affx_fusionPINVOKE.CCELFileData_GetAlgorithmParameter(swigCPtr, tag);
    return ret;
  }

  public string GetAlgorithmParameterTag(int index) {
    string ret = affx_fusionPINVOKE.CCELFileData_GetAlgorithmParameterTag(swigCPtr, index);
    return ret;
  }

  public int GetNumberAlgorithmParameters() {
    int ret = affx_fusionPINVOKE.CCELFileData_GetNumberAlgorithmParameters(swigCPtr);
    return ret;
  }

  public string GetAlgorithmParameters() {
    string ret = affx_fusionPINVOKE.CCELFileData_GetAlgorithmParameters(swigCPtr);
    return ret;
  }

  public string GetDatHeader() {
    string ret = affx_fusionPINVOKE.CCELFileData_GetDatHeader(swigCPtr);
    return ret;
  }

  public string GetChipType() {
    string ret = affx_fusionPINVOKE.CCELFileData_GetChipType(swigCPtr);
    return ret;
  }

  public int GetCellMargin() {
    int ret = affx_fusionPINVOKE.CCELFileData_GetCellMargin(swigCPtr);
    return ret;
  }

  public uint GetNumOutliers() {
    uint ret = affx_fusionPINVOKE.CCELFileData_GetNumOutliers(swigCPtr);
    return ret;
  }

  public uint GetNumMasked() {
    uint ret = affx_fusionPINVOKE.CCELFileData_GetNumMasked(swigCPtr);
    return ret;
  }

  public GridCoordinatesType GetGridCorners() {
    GridCoordinatesType ret = new GridCoordinatesType(affx_fusionPINVOKE.CCELFileData_GetGridCorners(swigCPtr), true);
    return ret;
  }

  public int IndexToX(int index) {
    int ret = affx_fusionPINVOKE.CCELFileData_IndexToX(swigCPtr, index);
    return ret;
  }

  public int IndexToY(int index) {
    int ret = affx_fusionPINVOKE.CCELFileData_IndexToY(swigCPtr, index);
    return ret;
  }

  public int XYToIndex(int x, int y) {
    int ret = affx_fusionPINVOKE.CCELFileData_XYToIndex__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public static int XYToIndex(int x, int y, int r, int c) {
    int ret = affx_fusionPINVOKE.CCELFileData_XYToIndex__SWIG_1(x, y, r, c);
    return ret;
  }

  public void GetEntry(int index, CELFileEntryType entry) {
    affx_fusionPINVOKE.CCELFileData_GetEntry__SWIG_0(swigCPtr, index, CELFileEntryType.getCPtr(entry));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetEntry(int x, int y, CELFileEntryType entry) {
    affx_fusionPINVOKE.CCELFileData_GetEntry__SWIG_1(swigCPtr, x, y, CELFileEntryType.getCPtr(entry));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTranscriptomeEntry(int index, CELFileTranscriptomeEntryType entry) {
    affx_fusionPINVOKE.CCELFileData_GetTranscriptomeEntry__SWIG_0(swigCPtr, index, CELFileTranscriptomeEntryType.getCPtr(entry));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTranscriptomeEntry(int x, int y, CELFileTranscriptomeEntryType entry) {
    affx_fusionPINVOKE.CCELFileData_GetTranscriptomeEntry__SWIG_1(swigCPtr, x, y, CELFileTranscriptomeEntryType.getCPtr(entry));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetIntensity(int index) {
    float ret = affx_fusionPINVOKE.CCELFileData_GetIntensity__SWIG_0(swigCPtr, index);
    return ret;
  }

  public float GetIntensity(int x, int y) {
    float ret = affx_fusionPINVOKE.CCELFileData_GetIntensity__SWIG_1(swigCPtr, x, y);
    return ret;
  }

  public float GetStdv(int index) {
    float ret = affx_fusionPINVOKE.CCELFileData_GetStdv__SWIG_0(swigCPtr, index);
    return ret;
  }

  public float GetStdv(int x, int y) {
    float ret = affx_fusionPINVOKE.CCELFileData_GetStdv__SWIG_1(swigCPtr, x, y);
    return ret;
  }

  public short GetPixels(int index) {
    short ret = affx_fusionPINVOKE.CCELFileData_GetPixels__SWIG_0(swigCPtr, index);
    return ret;
  }

  public short GetPixels(int x, int y) {
    short ret = affx_fusionPINVOKE.CCELFileData_GetPixels__SWIG_1(swigCPtr, x, y);
    return ret;
  }

  public bool IsMasked(int x, int y) {
    bool ret = affx_fusionPINVOKE.CCELFileData_IsMasked__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public bool IsMasked(int index) {
    bool ret = affx_fusionPINVOKE.CCELFileData_IsMasked__SWIG_1(swigCPtr, index);
    return ret;
  }

  public bool IsOutlier(int x, int y) {
    bool ret = affx_fusionPINVOKE.CCELFileData_IsOutlier__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public bool IsOutlier(int index) {
    bool ret = affx_fusionPINVOKE.CCELFileData_IsOutlier__SWIG_1(swigCPtr, index);
    return ret;
  }

  public void Close() {
    affx_fusionPINVOKE.CCELFileData_Close(swigCPtr);
  }

  public uint GetFileSize() {
    uint ret = affx_fusionPINVOKE.CCELFileData_GetFileSize(swigCPtr);
    return ret;
  }

  public bool Exists() {
    bool ret = affx_fusionPINVOKE.CCELFileData_Exists(swigCPtr);
    return ret;
  }

  public bool ReadHeader() {
    bool ret = affx_fusionPINVOKE.CCELFileData_ReadHeader(swigCPtr);
    return ret;
  }

  public bool Read(bool bIncludeMaskAndOutliers) {
    bool ret = affx_fusionPINVOKE.CCELFileData_Read__SWIG_0(swigCPtr, bIncludeMaskAndOutliers);
    return ret;
  }

  public bool Read() {
    bool ret = affx_fusionPINVOKE.CCELFileData_Read__SWIG_1(swigCPtr);
    return ret;
  }

  public bool IsXDACompatibleFile() {
    bool ret = affx_fusionPINVOKE.CCELFileData_IsXDACompatibleFile(swigCPtr);
    return ret;
  }

  public bool IsTranscriptomeBcelFile() {
    bool ret = affx_fusionPINVOKE.CCELFileData_IsTranscriptomeBcelFile(swigCPtr);
    return ret;
  }

  public bool IsCompactCelFile() {
    bool ret = affx_fusionPINVOKE.CCELFileData_IsCompactCelFile(swigCPtr);
    return ret;
  }

  public bool ReadEx(string filename, int nState) {
    bool ret = affx_fusionPINVOKE.CCELFileData_ReadEx__SWIG_0(swigCPtr, filename, nState);
    return ret;
  }

  public bool ReadEx(string filename) {
    bool ret = affx_fusionPINVOKE.CCELFileData_ReadEx__SWIG_1(swigCPtr, filename);
    return ret;
  }

  public bool ReadEx() {
    bool ret = affx_fusionPINVOKE.CCELFileData_ReadEx__SWIG_2(swigCPtr);
    return ret;
  }

  public int GetReadState() {
    int ret = affx_fusionPINVOKE.CCELFileData_GetReadState(swigCPtr);
    return ret;
  }

  public void Clear() {
    affx_fusionPINVOKE.CCELFileData_Clear(swigCPtr);
  }

  public int GetFileFormat() {
    int ret = affx_fusionPINVOKE.CCELFileData_GetFileFormat(swigCPtr);
    return ret;
  }

  public void SetFileFormat(int i) {
    affx_fusionPINVOKE.CCELFileData_SetFileFormat(swigCPtr, i);
  }

  public void SetAlgorithmName(string str) {
    affx_fusionPINVOKE.CCELFileData_SetAlgorithmName(swigCPtr, str);
  }

  public void AddAlgorithmParameter(string tag, string value) {
    affx_fusionPINVOKE.CCELFileData_AddAlgorithmParameter(swigCPtr, tag, value);
  }

  public void SetDimensions(int rows, int cols) {
    affx_fusionPINVOKE.CCELFileData_SetDimensions(swigCPtr, rows, cols);
  }

  public void SetChipType(string str) {
    affx_fusionPINVOKE.CCELFileData_SetChipType(swigCPtr, str);
  }

  public void SetMargin(int margin) {
    affx_fusionPINVOKE.CCELFileData_SetMargin(swigCPtr, margin);
  }

  public void SetGridCorners(GridCoordinatesType grid) {
    affx_fusionPINVOKE.CCELFileData_SetGridCorners(swigCPtr, GridCoordinatesType.getCPtr(grid));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetCellEntry(int x, int y, CELFileEntryType pEntry) {
    affx_fusionPINVOKE.CCELFileData_SetCellEntry__SWIG_0(swigCPtr, x, y, CELFileEntryType.getCPtr(pEntry));
  }

  public void SetCellEntry(int index, CELFileEntryType pEntry) {
    affx_fusionPINVOKE.CCELFileData_SetCellEntry__SWIG_1(swigCPtr, index, CELFileEntryType.getCPtr(pEntry));
  }

  public void AllocateEntries() {
    affx_fusionPINVOKE.CCELFileData_AllocateEntries(swigCPtr);
  }

  public void SetTranscriptomeCellEntry(int x, int y, CELFileTranscriptomeEntryType pEntry) {
    affx_fusionPINVOKE.CCELFileData_SetTranscriptomeCellEntry__SWIG_0(swigCPtr, x, y, CELFileTranscriptomeEntryType.getCPtr(pEntry));
  }

  public void SetTranscriptomeCellEntry(int index, CELFileTranscriptomeEntryType pEntry) {
    affx_fusionPINVOKE.CCELFileData_SetTranscriptomeCellEntry__SWIG_1(swigCPtr, index, CELFileTranscriptomeEntryType.getCPtr(pEntry));
  }

  public void AllocateTranscriptomeEntries() {
    affx_fusionPINVOKE.CCELFileData_AllocateTranscriptomeEntries(swigCPtr);
  }

  public void SetIntensity(int index, float intensity) {
    affx_fusionPINVOKE.CCELFileData_SetIntensity__SWIG_0(swigCPtr, index, intensity);
  }

  public void SetIntensity(int x, int y, float intensity) {
    affx_fusionPINVOKE.CCELFileData_SetIntensity__SWIG_1(swigCPtr, x, y, intensity);
  }

  public void SetStdv(int index, float stdev) {
    affx_fusionPINVOKE.CCELFileData_SetStdv__SWIG_0(swigCPtr, index, stdev);
  }

  public void SetStdv(int x, int y, float stdev) {
    affx_fusionPINVOKE.CCELFileData_SetStdv__SWIG_1(swigCPtr, x, y, stdev);
  }

  public void SetPixels(int index, short pixels) {
    affx_fusionPINVOKE.CCELFileData_SetPixels__SWIG_0(swigCPtr, index, pixels);
  }

  public void SetPixels(int x, int y, short pixels) {
    affx_fusionPINVOKE.CCELFileData_SetPixels__SWIG_1(swigCPtr, x, y, pixels);
  }

  public void SetMask(int index, bool mask) {
    affx_fusionPINVOKE.CCELFileData_SetMask__SWIG_0(swigCPtr, index, mask);
  }

  public void SetMask(int x, int y, bool masked) {
    affx_fusionPINVOKE.CCELFileData_SetMask__SWIG_1(swigCPtr, x, y, masked);
  }

  public void SetOutlier(int index, bool outlier) {
    affx_fusionPINVOKE.CCELFileData_SetOutlier__SWIG_0(swigCPtr, index, outlier);
  }

  public void SetOutlier(int x, int y, bool outlier) {
    affx_fusionPINVOKE.CCELFileData_SetOutlier__SWIG_1(swigCPtr, x, y, outlier);
  }

  public void Munmap() {
    affx_fusionPINVOKE.CCELFileData_Munmap(swigCPtr);
  }

  public void EnsureNotMmapped() {
    affx_fusionPINVOKE.CCELFileData_EnsureNotMmapped(swigCPtr);
  }

  public static readonly int TEXT_CEL = affx_fusionPINVOKE.get_CCELFileData_TEXT_CEL();
  public static readonly int XDA_BCEL = affx_fusionPINVOKE.get_CCELFileData_XDA_BCEL();
  public static readonly int TRANSCRIPTOME_BCEL = affx_fusionPINVOKE.get_CCELFileData_TRANSCRIPTOME_BCEL();
  public static readonly int COMPACT_BCEL = affx_fusionPINVOKE.get_CCELFileData_COMPACT_BCEL();

  public static readonly int CEL_ALL = affx_fusionPINVOKE.get_CCELFileData_CEL_ALL();
  public static readonly int CEL_DATA = affx_fusionPINVOKE.get_CCELFileData_CEL_DATA();
  public static readonly int CEL_OUTLIER = affx_fusionPINVOKE.get_CCELFileData_CEL_OUTLIER();
  public static readonly int CEL_MASK = affx_fusionPINVOKE.get_CCELFileData_CEL_MASK();

}
