/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CDFFileReader : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CDFFileReader(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CDFFileReader obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CDFFileReader() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CDFFileReader(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CDFFileReader() : this(affx_fusionPINVOKE.new_CDFFileReader(), true) {
  }

  public string GetFilename() {
    string ret = affx_fusionPINVOKE.CDFFileReader_GetFilename(swigCPtr);
    return ret;
  }

  public void SetFilename(string name) {
    affx_fusionPINVOKE.CDFFileReader_SetFilename(swigCPtr, name);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Read(CDFData data, CDFFileReader.ReadMode mode) {
    affx_fusionPINVOKE.CDFFileReader_Read__SWIG_0(swigCPtr, CDFData.getCPtr(data), (int)mode);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Read(CDFData data) {
    affx_fusionPINVOKE.CDFFileReader_Read__SWIG_1(swigCPtr, CDFData.getCPtr(data));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public enum ReadMode {
    ReadSequential,
    ReadByProbeSetNumber,
    ReadByProbeSetName
  }

}
