/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CDFProbeInformation : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CDFProbeInformation(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CDFProbeInformation obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CDFProbeInformation() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CDFProbeInformation(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CDFProbeInformation() : this(affx_fusionPINVOKE.new_CDFProbeInformation(), true) {
  }

  public uint GetListIndex() {
    uint ret = affx_fusionPINVOKE.CDFProbeInformation_GetListIndex(swigCPtr);
    return ret;
  }

  public int GetExpos() {
    int ret = affx_fusionPINVOKE.CDFProbeInformation_GetExpos(swigCPtr);
    return ret;
  }

  public ushort GetX() {
    ushort ret = affx_fusionPINVOKE.CDFProbeInformation_GetX(swigCPtr);
    return ret;
  }

  public ushort GetY() {
    ushort ret = affx_fusionPINVOKE.CDFProbeInformation_GetY(swigCPtr);
    return ret;
  }

  public char GetPBase() {
    char ret = affx_fusionPINVOKE.CDFProbeInformation_GetPBase(swigCPtr);
    return ret;
  }

  public char GetTBase() {
    char ret = affx_fusionPINVOKE.CDFProbeInformation_GetTBase(swigCPtr);
    return ret;
  }

}
