/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CDFQCProbeInformation : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CDFQCProbeInformation(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CDFQCProbeInformation obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CDFQCProbeInformation() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CDFQCProbeInformation(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CDFQCProbeInformation() : this(affx_fusionPINVOKE.new_CDFQCProbeInformation(), true) {
  }

  public ushort GetX() {
    ushort ret = affx_fusionPINVOKE.CDFQCProbeInformation_GetX(swigCPtr);
    return ret;
  }

  public ushort GetY() {
    ushort ret = affx_fusionPINVOKE.CDFQCProbeInformation_GetY(swigCPtr);
    return ret;
  }

  public byte GetPLen() {
    byte ret = affx_fusionPINVOKE.CDFQCProbeInformation_GetPLen(swigCPtr);
    return ret;
  }

  public bool IsPerfectMatchProbe() {
    bool ret = affx_fusionPINVOKE.CDFQCProbeInformation_IsPerfectMatchProbe(swigCPtr);
    return ret;
  }

  public bool IsBackgroundProbe() {
    bool ret = affx_fusionPINVOKE.CDFQCProbeInformation_IsBackgroundProbe(swigCPtr);
    return ret;
  }

}
