/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CDFQCProbeSetInformation : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CDFQCProbeSetInformation(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CDFQCProbeSetInformation obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CDFQCProbeSetInformation() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CDFQCProbeSetInformation(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CDFQCProbeSetInformation() : this(affx_fusionPINVOKE.new_CDFQCProbeSetInformation(), true) {
  }

  public SWIGTYPE_p_std__wstring GetQCProbeSetType() {
    SWIGTYPE_p_std__wstring ret = new SWIGTYPE_p_std__wstring(affx_fusionPINVOKE.CDFQCProbeSetInformation_GetQCProbeSetType(swigCPtr), true);
    return ret;
  }

  public int GetNumCells() {
    int ret = affx_fusionPINVOKE.CDFQCProbeSetInformation_GetNumCells(swigCPtr);
    return ret;
  }

  public void GetProbeInformation(int index, CDFQCProbeInformation info) {
    affx_fusionPINVOKE.CDFQCProbeSetInformation_GetProbeInformation(swigCPtr, index, CDFQCProbeInformation.getCPtr(info));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

}
