/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CEXPFileData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CEXPFileData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CEXPFileData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CEXPFileData() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CEXPFileData(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CEXPFileData() : this(affx_fusionPINVOKE.new_CEXPFileData(), true) {
  }

  public void SetFileName(string name) {
    affx_fusionPINVOKE.CEXPFileData_SetFileName(swigCPtr, name);
  }

  public string GetFileName() {
    string ret = affx_fusionPINVOKE.CEXPFileData_GetFileName(swigCPtr);
    return ret;
  }

  public string GetArrayType() {
    string ret = affx_fusionPINVOKE.CEXPFileData_GetArrayType(swigCPtr);
    return ret;
  }

  public void SetArrayType(string arrayType) {
    affx_fusionPINVOKE.CEXPFileData_SetArrayType(swigCPtr, arrayType);
  }

  public bool Read() {
    bool ret = affx_fusionPINVOKE.CEXPFileData_Read(swigCPtr);
    return ret;
  }

  public bool Exists() {
    bool ret = affx_fusionPINVOKE.CEXPFileData_Exists(swigCPtr);
    return ret;
  }

  public void Clear() {
    affx_fusionPINVOKE.CEXPFileData_Clear(swigCPtr);
  }

  public SWIGTYPE_p_std__listT_TagValuePairType_t GetScanParameters() {
    SWIGTYPE_p_std__listT_TagValuePairType_t ret = new SWIGTYPE_p_std__listT_TagValuePairType_t(affx_fusionPINVOKE.CEXPFileData_GetScanParameters(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__listT_TagValuePairType_t GetHybParameters() {
    SWIGTYPE_p_std__listT_TagValuePairType_t ret = new SWIGTYPE_p_std__listT_TagValuePairType_t(affx_fusionPINVOKE.CEXPFileData_GetHybParameters(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__listT_TagValuePairType_t GetSampleParameters() {
    SWIGTYPE_p_std__listT_TagValuePairType_t ret = new SWIGTYPE_p_std__listT_TagValuePairType_t(affx_fusionPINVOKE.CEXPFileData_GetSampleParameters(swigCPtr), false);
    return ret;
  }

}
