/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CheckSum : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CheckSum(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CheckSum obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CheckSum() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CheckSum(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public static ushort OnesComplementCheckSum(SWIGTYPE_p_void addr, uint size) {
    ushort ret = affx_fusionPINVOKE.CheckSum_OnesComplementCheckSum(SWIGTYPE_p_void.getCPtr(addr), size);
    return ret;
  }

  public CheckSum() : this(affx_fusionPINVOKE.new_CheckSum(), true) {
  }

}
