/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CoordinatePoint : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CoordinatePoint(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CoordinatePoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CoordinatePoint() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CoordinatePoint(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public int x {
    set {
      affx_fusionPINVOKE.set_CoordinatePoint_x(swigCPtr, value);
    } 
    get {
      int ret = affx_fusionPINVOKE.get_CoordinatePoint_x(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      affx_fusionPINVOKE.set_CoordinatePoint_y(swigCPtr, value);
    } 
    get {
      int ret = affx_fusionPINVOKE.get_CoordinatePoint_y(swigCPtr);
      return ret;
    } 
  }

  public CoordinatePoint() : this(affx_fusionPINVOKE.new_CoordinatePoint(), true) {
  }

}
