/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CPSIFileData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CPSIFileData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CPSIFileData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CPSIFileData() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_CPSIFileData(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CPSIFileData() : this(affx_fusionPINVOKE.new_CPSIFileData(), true) {
  }

  public void SetFileName(string name) {
    affx_fusionPINVOKE.CPSIFileData_SetFileName(swigCPtr, name);
  }

  public string GetFileName() {
    string ret = affx_fusionPINVOKE.CPSIFileData_GetFileName(swigCPtr);
    return ret;
  }

  public int GetProbeSetCount() {
    int ret = affx_fusionPINVOKE.CPSIFileData_GetProbeSetCount(swigCPtr);
    return ret;
  }

  public string GetProbeSetName(int index) {
    string ret = affx_fusionPINVOKE.CPSIFileData_GetProbeSetName(swigCPtr, index);
    return ret;
  }

  public int GetProbePairs(int index) {
    int ret = affx_fusionPINVOKE.CPSIFileData_GetProbePairs(swigCPtr, index);
    return ret;
  }

  public bool Read() {
    bool ret = affx_fusionPINVOKE.CPSIFileData_Read(swigCPtr);
    return ret;
  }

  public bool Exists() {
    bool ret = affx_fusionPINVOKE.CPSIFileData_Exists(swigCPtr);
    return ret;
  }

  public void Clear() {
    affx_fusionPINVOKE.CPSIFileData_Clear(swigCPtr);
  }

}
