/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DataGroupHeaderReader : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DataGroupHeaderReader(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DataGroupHeaderReader obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DataGroupHeaderReader() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_DataGroupHeaderReader(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public DataGroupHeaderReader() : this(affx_fusionPINVOKE.new_DataGroupHeaderReader(), true) {
  }

  public void ReadAllMinimumInfo(SWIGTYPE_p_std__ifstream fs, FileHeader fh, uint dataGroupCnt) {
    affx_fusionPINVOKE.DataGroupHeaderReader_ReadAllMinimumInfo(swigCPtr, SWIGTYPE_p_std__ifstream.getCPtr(fs), FileHeader.getCPtr(fh), dataGroupCnt);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ReadAll(SWIGTYPE_p_std__ifstream fileStream, FileHeader fh, uint dataGroupCnt) {
    affx_fusionPINVOKE.DataGroupHeaderReader_ReadAll(swigCPtr, SWIGTYPE_p_std__ifstream.getCPtr(fileStream), FileHeader.getCPtr(fh), dataGroupCnt);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint ReadMinimumInfo(SWIGTYPE_p_std__ifstream fileStream, DataGroupHeader dch) {
    uint ret = affx_fusionPINVOKE.DataGroupHeaderReader_ReadMinimumInfo(swigCPtr, SWIGTYPE_p_std__ifstream.getCPtr(fileStream), DataGroupHeader.getCPtr(dch));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint Read(SWIGTYPE_p_std__ifstream fileStream, DataGroupHeader dch) {
    uint ret = affx_fusionPINVOKE.DataGroupHeaderReader_Read(swigCPtr, SWIGTYPE_p_std__ifstream.getCPtr(fileStream), DataGroupHeader.getCPtr(dch));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint ReadHeader(SWIGTYPE_p_std__ifstream fileStream, DataGroupHeader dch) {
    uint ret = affx_fusionPINVOKE.DataGroupHeaderReader_ReadHeader(swigCPtr, SWIGTYPE_p_std__ifstream.getCPtr(fileStream), DataGroupHeader.getCPtr(dch));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
