/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DataGroupReader : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DataGroupReader(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DataGroupReader obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DataGroupReader() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_DataGroupReader(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public DataGroupReader(SWIGTYPE_p_std__ifstream o, DataGroupHeader hdr) : this(affx_fusionPINVOKE.new_DataGroupReader(SWIGTYPE_p_std__ifstream.getCPtr(o), DataGroupHeader.getCPtr(hdr)), true) {
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetDataSetCnt() {
    int ret = affx_fusionPINVOKE.DataGroupReader_GetDataSetCnt(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__wstring GetDataGroupName() {
    SWIGTYPE_p_std__wstring ret = new SWIGTYPE_p_std__wstring(affx_fusionPINVOKE.DataGroupReader_GetDataGroupName(swigCPtr), true);
    return ret;
  }

  public DataSetReader GetDataSetReader(int index) {
    DataSetReader ret = new DataSetReader(affx_fusionPINVOKE.DataGroupReader_GetDataSetReader__SWIG_0(swigCPtr, index), true);
    return ret;
  }

  public DataSetReader GetDataSetReader(SWIGTYPE_p_std__wstring name) {
    DataSetReader ret = new DataSetReader(affx_fusionPINVOKE.DataGroupReader_GetDataSetReader__SWIG_1(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(name)), true);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
