/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DttArrayData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DttArrayData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DttArrayData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DttArrayData() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_DttArrayData(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public DttArrayData() : this(affx_fusionPINVOKE.new_DttArrayData(), true) {
  }

  public string GetArrayType() {
    string ret = affx_fusionPINVOKE.DttArrayData_GetArrayType(swigCPtr);
    return ret;
  }

  public void SetArrayType(string aType) {
    affx_fusionPINVOKE.DttArrayData_SetArrayType(swigCPtr, aType);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetExperimentName() {
    string ret = affx_fusionPINVOKE.DttArrayData_GetExperimentName(swigCPtr);
    return ret;
  }

  public void SetExperimentName(string name) {
    affx_fusionPINVOKE.DttArrayData_SetExperimentName(swigCPtr, name);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__listTaffymetrix_dttarray___AttributeNameValueType_t Attributes() {
    SWIGTYPE_p_std__listTaffymetrix_dttarray___AttributeNameValueType_t ret = new SWIGTYPE_p_std__listTaffymetrix_dttarray___AttributeNameValueType_t(affx_fusionPINVOKE.DttArrayData_Attributes(swigCPtr), false);
    return ret;
  }

  public void Clear() {
    affx_fusionPINVOKE.DttArrayData_Clear(swigCPtr);
  }

}
