/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FPoint : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FPoint(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FPoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FPoint() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_FPoint(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public float x {
    set {
      affx_fusionPINVOKE.set_FPoint_x(swigCPtr, value);
    } 
    get {
      float ret = affx_fusionPINVOKE.get_FPoint_x(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      affx_fusionPINVOKE.set_FPoint_y(swigCPtr, value);
    } 
    get {
      float ret = affx_fusionPINVOKE.get_FPoint_y(swigCPtr);
      return ret;
    } 
  }

  public bool FPoint_equals(FPoint lhs) {
    bool ret = affx_fusionPINVOKE.FPoint_FPoint_equals(swigCPtr, FPoint.getCPtr(lhs));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool FPoint_not_equals(FPoint lhs) {
    bool ret = affx_fusionPINVOKE.FPoint_FPoint_not_equals(swigCPtr, FPoint.getCPtr(lhs));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FPoint() : this(affx_fusionPINVOKE.new_FPoint(), true) {
  }

}
