/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FusionTagValuePairType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FusionTagValuePairType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FusionTagValuePairType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FusionTagValuePairType() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_FusionTagValuePairType(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public SWIGTYPE_p_std__wstring Tag {
    set {
      affx_fusionPINVOKE.set_FusionTagValuePairType_Tag(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
      if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__wstring ret = new SWIGTYPE_p_std__wstring(affx_fusionPINVOKE.get_FusionTagValuePairType_Tag(swigCPtr), true);
      if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__wstring Value {
    set {
      affx_fusionPINVOKE.set_FusionTagValuePairType_Value(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(value));
      if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__wstring ret = new SWIGTYPE_p_std__wstring(affx_fusionPINVOKE.get_FusionTagValuePairType_Value(swigCPtr), true);
      if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public FusionTagValuePairType FusionTagValuePairType_assign(FusionTagValuePairType vp) {
    FusionTagValuePairType ret = new FusionTagValuePairType(affx_fusionPINVOKE.FusionTagValuePairType_FusionTagValuePairType_assign(swigCPtr, FusionTagValuePairType.getCPtr(vp)), true);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool FusionTagValuePairType_equals_obj(FusionTagValuePairType vp) {
    bool ret = affx_fusionPINVOKE.FusionTagValuePairType_FusionTagValuePairType_equals_obj(swigCPtr, FusionTagValuePairType.getCPtr(vp));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool FusionTagValuePairType_equals_tag(SWIGTYPE_p_wchar_t tag) {
    bool ret = affx_fusionPINVOKE.FusionTagValuePairType_FusionTagValuePairType_equals_tag(swigCPtr, SWIGTYPE_p_wchar_t.getCPtr(tag));
    return ret;
  }

  public ParameterNameValueType DetailedType() {
    ParameterNameValueType ret = new ParameterNameValueType(affx_fusionPINVOKE.FusionTagValuePairType_DetailedType(swigCPtr), false);
    return ret;
  }

  public FusionTagValuePairType() : this(affx_fusionPINVOKE.new_FusionTagValuePairType(), true) {
  }

}
