/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FusionCDFQCProbeInformation : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FusionCDFQCProbeInformation(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FusionCDFQCProbeInformation obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FusionCDFQCProbeInformation() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_FusionCDFQCProbeInformation(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public FusionCDFQCProbeInformation() : this(affx_fusionPINVOKE.new_FusionCDFQCProbeInformation(), true) {
  }

  public int GetX() {
    int ret = affx_fusionPINVOKE.FusionCDFQCProbeInformation_GetX(swigCPtr);
    return ret;
  }

  public int GetY() {
    int ret = affx_fusionPINVOKE.FusionCDFQCProbeInformation_GetY(swigCPtr);
    return ret;
  }

  public int GetPLen() {
    int ret = affx_fusionPINVOKE.FusionCDFQCProbeInformation_GetPLen(swigCPtr);
    return ret;
  }

  public bool IsPerfectMatchProbe() {
    bool ret = affx_fusionPINVOKE.FusionCDFQCProbeInformation_IsPerfectMatchProbe(swigCPtr);
    return ret;
  }

  public bool IsBackgroundProbe() {
    bool ret = affx_fusionPINVOKE.FusionCDFQCProbeInformation_IsBackgroundProbe(swigCPtr);
    return ret;
  }

}
