/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FusionCDFQCProbeSetInformation : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FusionCDFQCProbeSetInformation(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FusionCDFQCProbeSetInformation obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FusionCDFQCProbeSetInformation() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_FusionCDFQCProbeSetInformation(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public GeneChipQCProbeSetType GetQCProbeSetType() {
    GeneChipQCProbeSetType ret = (GeneChipQCProbeSetType)affx_fusionPINVOKE.FusionCDFQCProbeSetInformation_GetQCProbeSetType(swigCPtr);
    return ret;
  }

  public int GetNumCells() {
    int ret = affx_fusionPINVOKE.FusionCDFQCProbeSetInformation_GetNumCells(swigCPtr);
    return ret;
  }

  public void GetProbeInformation(int index, FusionCDFQCProbeInformation info) {
    affx_fusionPINVOKE.FusionCDFQCProbeSetInformation_GetProbeInformation(swigCPtr, index, FusionCDFQCProbeInformation.getCPtr(info));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public FusionCDFQCProbeSetInformation() : this(affx_fusionPINVOKE.new_FusionCDFQCProbeSetInformation(), true) {
  }

}
