/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FusionUniversalProbeSetResults : FusionProbeSetResults {
  private HandleRef swigCPtr;

  internal FusionUniversalProbeSetResults(IntPtr cPtr, bool cMemoryOwn) : base(affx_fusionPINVOKE.FusionUniversalProbeSetResultsUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FusionUniversalProbeSetResults obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FusionUniversalProbeSetResults() {
    Dispose();
  }

  public override void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_FusionUniversalProbeSetResults(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
    base.Dispose();
  }

  public float GetBackground() {
    float ret = affx_fusionPINVOKE.FusionUniversalProbeSetResults_GetBackground(swigCPtr);
    return ret;
  }

  public void SetBackground(float bg) {
    affx_fusionPINVOKE.FusionUniversalProbeSetResults_SetBackground(swigCPtr, bg);
  }

  public void Clear() {
    affx_fusionPINVOKE.FusionUniversalProbeSetResults_Clear(swigCPtr);
  }

  public FusionUniversalProbeSetResults FusionUniversalProbeSetResults_assign(FusionUniversalProbeSetResults src) {
    FusionUniversalProbeSetResults ret = new FusionUniversalProbeSetResults(affx_fusionPINVOKE.FusionUniversalProbeSetResults_FusionUniversalProbeSetResults_assign(swigCPtr, FusionUniversalProbeSetResults.getCPtr(src)), true);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FusionUniversalProbeSetResults() : this(affx_fusionPINVOKE.new_FusionUniversalProbeSetResults(), true) {
  }

}
