/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FusionBaseCallType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FusionBaseCallType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FusionBaseCallType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FusionBaseCallType() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_FusionBaseCallType(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public FusionBaseCallType() : this(affx_fusionPINVOKE.new_FusionBaseCallType__SWIG_0(), true) {
  }

  public FusionBaseCallType(int p, char c) : this(affx_fusionPINVOKE.new_FusionBaseCallType__SWIG_1(p, c), true) {
  }

  public void Clear() {
    affx_fusionPINVOKE.FusionBaseCallType_Clear(swigCPtr);
  }

  public int GetPosition() {
    int ret = affx_fusionPINVOKE.FusionBaseCallType_GetPosition(swigCPtr);
    return ret;
  }

  public char GetCall() {
    char ret = affx_fusionPINVOKE.FusionBaseCallType_GetCall(swigCPtr);
    return ret;
  }

  public void SetPosition(int p) {
    affx_fusionPINVOKE.FusionBaseCallType_SetPosition(swigCPtr, p);
  }

  public void SetCall(char p) {
    affx_fusionPINVOKE.FusionBaseCallType_SetCall(swigCPtr, p);
  }

}
