/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FusionGenotypeProbeSetResults : FusionProbeSetResults {
  private HandleRef swigCPtr;

  internal FusionGenotypeProbeSetResults(IntPtr cPtr, bool cMemoryOwn) : base(affx_fusionPINVOKE.FusionGenotypeProbeSetResultsUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FusionGenotypeProbeSetResults obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FusionGenotypeProbeSetResults() {
    Dispose();
  }

  public override void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_FusionGenotypeProbeSetResults(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
    base.Dispose();
  }

  public void Clear() {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_Clear(swigCPtr);
  }

  public byte GetAlleleCall() {
    byte ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetAlleleCall(swigCPtr);
    return ret;
  }

  public float GetConfidence() {
    float ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetConfidence(swigCPtr);
    return ret;
  }

  public float GetRAS1() {
    float ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetRAS1(swigCPtr);
    return ret;
  }

  public float GetRAS2() {
    float ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetRAS2(swigCPtr);
    return ret;
  }

  public float GetPValueAA() {
    float ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetPValueAA(swigCPtr);
    return ret;
  }

  public float GetPValueAB() {
    float ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetPValueAB(swigCPtr);
    return ret;
  }

  public float GetPValueBB() {
    float ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetPValueBB(swigCPtr);
    return ret;
  }

  public float GetPValueNoCall() {
    float ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetPValueNoCall(swigCPtr);
    return ret;
  }

  public void SetAlleleCall(byte p) {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_SetAlleleCall(swigCPtr, p);
  }

  public void SetConfidence(float p) {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_SetConfidence(swigCPtr, p);
  }

  public void SetRAS1(float p) {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_SetRAS1(swigCPtr, p);
  }

  public void SetRAS2(float p) {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_SetRAS2(swigCPtr, p);
  }

  public void SetPValueAA(float p) {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_SetPValueAA(swigCPtr, p);
  }

  public void SetPValueAB(float p) {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_SetPValueAB(swigCPtr, p);
  }

  public void SetPValueBB(float p) {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_SetPValueBB(swigCPtr, p);
  }

  public void SetPValueNoCall(float p) {
    affx_fusionPINVOKE.FusionGenotypeProbeSetResults_SetPValueNoCall(swigCPtr, p);
  }

  public string GetAlleleCallString() {
    string ret = affx_fusionPINVOKE.FusionGenotypeProbeSetResults_GetAlleleCallString(swigCPtr);
    return ret;
  }

  public FusionGenotypeProbeSetResults FusionGenotypeProbeSetResults_assign(FusionGenotypeProbeSetResults src) {
    FusionGenotypeProbeSetResults ret = new FusionGenotypeProbeSetResults(affx_fusionPINVOKE.FusionGenotypeProbeSetResults_FusionGenotypeProbeSetResults_assign(swigCPtr, FusionGenotypeProbeSetResults.getCPtr(src)), true);
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FusionGenotypeProbeSetResults() : this(affx_fusionPINVOKE.new_FusionGenotypeProbeSetResults(), true) {
  }

}
