/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum GeneChipQCProbeSetType {
  UnknownQCProbeSetType,
  CheckerboardNegativeQCProbeSetType,
  CheckerboardPositiveQCProbeSetType,
  HybNegativeQCProbeSetType,
  HybPositiveQCProbeSetType,
  TextFeaturesNegativeQCProbeSetType,
  TextFeaturesPositiveQCProbeSetType,
  CentralNegativeQCProbeSetType,
  CentralPositiveQCProbeSetType,
  GeneExpNegativeQCProbeSetType,
  GeneExpPositiveQCProbeSetType,
  CycleFidelityNegativeQCProbeSetType,
  CycleFidelityPositiveQCProbeSetType,
  CentralCrossNegativeQCProbeSetType,
  CentralCrossPositiveQCProbeSetType,
  CrossHybNegativeQCProbeSetType,
  CrossHybPositiveQCProbeSetType,
  SpatialNormalizationNegativeQCProbeSetType,
  SpatialNormalizationPositiveQCProbeSetType
}
