/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class GridCoordinatesType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GridCoordinatesType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GridCoordinatesType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GridCoordinatesType() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_GridCoordinatesType(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public CoordinatePoint upperleft {
    set {
      affx_fusionPINVOKE.set_GridCoordinatesType_upperleft(swigCPtr, CoordinatePoint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_GridCoordinatesType_upperleft(swigCPtr);
      CoordinatePoint ret = (cPtr == IntPtr.Zero) ? null : new CoordinatePoint(cPtr, false);
      return ret;
    } 
  }

  public CoordinatePoint upperright {
    set {
      affx_fusionPINVOKE.set_GridCoordinatesType_upperright(swigCPtr, CoordinatePoint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_GridCoordinatesType_upperright(swigCPtr);
      CoordinatePoint ret = (cPtr == IntPtr.Zero) ? null : new CoordinatePoint(cPtr, false);
      return ret;
    } 
  }

  public CoordinatePoint lowerright {
    set {
      affx_fusionPINVOKE.set_GridCoordinatesType_lowerright(swigCPtr, CoordinatePoint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_GridCoordinatesType_lowerright(swigCPtr);
      CoordinatePoint ret = (cPtr == IntPtr.Zero) ? null : new CoordinatePoint(cPtr, false);
      return ret;
    } 
  }

  public CoordinatePoint lowerleft {
    set {
      affx_fusionPINVOKE.set_GridCoordinatesType_lowerleft(swigCPtr, CoordinatePoint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_GridCoordinatesType_lowerleft(swigCPtr);
      CoordinatePoint ret = (cPtr == IntPtr.Zero) ? null : new CoordinatePoint(cPtr, false);
      return ret;
    } 
  }

  public GridCoordinatesType() : this(affx_fusionPINVOKE.new_GridCoordinatesType(), true) {
  }

}
