/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ProbeSetIndiciesType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ProbeSetIndiciesType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ProbeSetIndiciesType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ProbeSetIndiciesType() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_ProbeSetIndiciesType(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public SWIGTYPE_p_std__string probeSetName {
    set {
      affx_fusionPINVOKE.set_ProbeSetIndiciesType_probeSetName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_ProbeSetIndiciesType_probeSetName(swigCPtr);
      SWIGTYPE_p_std__string ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_std__string(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__listTint_t indicies {
    set {
      affx_fusionPINVOKE.set_ProbeSetIndiciesType_indicies(swigCPtr, SWIGTYPE_p_std__listTint_t.getCPtr(value));
      if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__listTint_t ret = new SWIGTYPE_p_std__listTint_t(affx_fusionPINVOKE.get_ProbeSetIndiciesType_indicies(swigCPtr), true);
      if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ProbeSetIndiciesType() : this(affx_fusionPINVOKE.new_ProbeSetIndiciesType(), true) {
  }

}
