/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Subgrid : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Subgrid(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Subgrid obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Subgrid() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_Subgrid(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public int row {
    set {
      affx_fusionPINVOKE.set_Subgrid_row(swigCPtr, value);
    } 
    get {
      int ret = affx_fusionPINVOKE.get_Subgrid_row(swigCPtr);
      return ret;
    } 
  }

  public int col {
    set {
      affx_fusionPINVOKE.set_Subgrid_col(swigCPtr, value);
    } 
    get {
      int ret = affx_fusionPINVOKE.get_Subgrid_col(swigCPtr);
      return ret;
    } 
  }

  public FRect pixelgrid {
    set {
      affx_fusionPINVOKE.set_Subgrid_pixelgrid(swigCPtr, FRect.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_Subgrid_pixelgrid(swigCPtr);
      FRect ret = (cPtr == IntPtr.Zero) ? null : new FRect(cPtr, false);
      return ret;
    } 
  }

  public Rect cellgrid {
    set {
      affx_fusionPINVOKE.set_Subgrid_cellgrid(swigCPtr, Rect.getCPtr(value));
    } 
    get {
      IntPtr cPtr = affx_fusionPINVOKE.get_Subgrid_cellgrid(swigCPtr);
      Rect ret = (cPtr == IntPtr.Zero) ? null : new Rect(cPtr, false);
      return ret;
    } 
  }

  public Subgrid() : this(affx_fusionPINVOKE.new_Subgrid(), true) {
  }

}
