/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class TextFileReader : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TextFileReader(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TextFileReader obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TextFileReader() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      affx_fusionPINVOKE.delete_TextFileReader(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public TextFileReader() : this(affx_fusionPINVOKE.new_TextFileReader(), true) {
  }

  public void ReadFile(string fileName, SWIGTYPE_p_std__mapTstd__string_std__string_t textData) {
    affx_fusionPINVOKE.TextFileReader_ReadFile__SWIG_0(swigCPtr, fileName, SWIGTYPE_p_std__mapTstd__string_std__string_t.getCPtr(textData));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ReadFile(SWIGTYPE_p_std__ifstream fileStream, SWIGTYPE_p_std__mapTstd__string_std__string_t textData) {
    affx_fusionPINVOKE.TextFileReader_ReadFile__SWIG_1(swigCPtr, SWIGTYPE_p_std__ifstream.getCPtr(fileStream), SWIGTYPE_p_std__mapTstd__string_std__string_t.getCPtr(textData));
    if (affx_fusionPINVOKE.SWIGPendingException.Pending) throw affx_fusionPINVOKE.SWIGPendingException.Retrieve();
  }

}
